### ISSUE TITLE
[Bug] markdown parentheses in link

### ISSUE THREAD

**Issue by TimerWolf** [go-gitea/gitea#10431]
- Gitea version (1.12.0+dev-360-g9ed4aeeaf):
- Git version: unknown
- Operating system: unknown
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
  - [x] Not relevant
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
  - [x] Not relevant
## Description

This is an other example of the markdown when you use title with "markdown" the parentheses make it unbalanced, and then the function will broke, but as you can see it works perfectly fine here in github.

So try the example here and see that it works fine, and the copy it in latest gitea build and see that the "markdown style" is broken while the clean html works just fine.

As always, hover the mouse over the "broken" and "works" to show "title tooltip" and it will show you the results. 

## Code

```markdown
| Test |
| -------- |
| [broken](https://: "This shows that () is broken when use it in the markdown style in the title") |
|  <a href="https://:" title="This shows that () works fine when use it in html style in the title">works</a> |
```

## Example

| Test |
| -------- |
| [broken](https://: "This shows that () is broken when use it in the markdown style in the title") |
| <a href="https://:" title="This shows that () works fine when use it in html style in the title">works</a> |

**Comment by zeripath** [comment]
In this case a link on try would have been very pertinent.

**Comment by zeripath** [comment]
https://try.gitea.io/arandomer/anudderrepo

Which does not appear to show the bug...

**Comment by jolheiser** [comment]
Likely fixed by https://github.com/go-gitea/gitea/pull/10371

**Comment by TimerWolf** [comment]
@zeripath: that is very strange, what commit would have fix that i use "1.11.0" and the problem is in that version. Maybe wait for the 1.12.0 to come out then and bump this if its still a problem.

@jolheiser: i don´t think so maybe i shoot my self in the foot here but the #10371 has nothing to do whit this as the title works in the "html" code, if it would be the same problem none of the example would have work in my test.

**Comment by zeripath** [comment]
No probs. It's the kind of think that the move to goldmark child have fixed.
