### ISSUE TITLE
Cannot push to repositories

### ISSUE THREAD

**Issue by pgaskin** [go-gitea/gitea#1073]
- Gitea version (or commit ref): bf24099114d75dbc625bc8385a0a7d969d0c3748
- Git version: 2.9.3
- Operating system:  Ubuntu 16.10
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io: Not sure
- Log gist: Nothing abnormal but this line in post-recieve log: `2017/02/26 11:32:59 [...io/gitea/cmd/hook.go:118 runHookPreReceive()] [F] Fail to detect force push: exit status 128 - fatal: Not a git repository: '.'`

## Description
I cannot push anything to any of my repos anymore. Everything else still works.

I have tried enabling protected branches, disabling it, and it still happens.

````
Counting objects: 13, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (12/12), done.
Writing objects: 100% (13/13), 14.26 MiB | 16.07 MiB/s, done.
Total 13 (delta 2), reused 0 (delta 0)
remote: Gitea: Internal error
remote: Fail to detect force push: exit status 128 - fatal: Not a git repository: '.'
remote: 
To git url here
 ! [remote rejected] master -> master (pre-receive hook declined)
````

**Comment by pgaskin** [comment]
@NormalRa and I have been looking into this. We have managed to fix one thing, but another problem appeared.

Here is the code for hook.go:
Add the import `"code.gitea.io/gitea/models/repo"`
Replace line 116 (`output, err := git.NewCommand("rev-list", oldCommitID, "^"+newCommitID).Run()`) with 
````
repo, err = GetRepositoryByID(repoID)
if err != nil {
    log.GitLogger.Fatal(2, "get repo path failed")
}
repoPath = repo.RepoPath()

output, err := git.NewCommand("rev-list", oldCommitID, "^"+newCommitID).RunInDir(repoPath)
````

The not a git repo error disappeared, but the following one appeared.
````
remote: Fail to detect force push: exit status 128 - fatal: bad object 0000000000000000000000000000000000000000
````

**Comment by dh-harald** [comment]
I'm on the latest docker image (1.0.0+341-gab462fb9)

I've tried to amend/force push into a repository (even if there's no protected branch):
```
remote: Gitea: Branch 'master' is protected from force push
To ssh://git@xxxx.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@xxxx.git'
```
So I've deleted the repository, and I've tried to push back into the empty repository (worked before):
```
remote: Gitea: Internal error
remote: Fail to detect force push: exit status 128 - fatal: bad object 0000000000000000000000000000000000000000
```

**Comment by pgaskin** [comment]
@dh-harald That is the error I get as well

**Comment by pgaskin** [comment]
I think that second error is if the repository or branch is empty. @dh-harald Is the repo empty?

**Comment by dh-harald** [comment]
Yes, the repository (on gitea) has been deleted and recreated...

**Comment by dh-harald** [comment]
I still can't push into empty repository (1.0.0+350-gc0f99e82):
```
remote: Gitea: Internal error
remote: Fail to detect force push: exit status 128 - fatal: bad object 0000000000000000000000000000000000000000
remote: 
To ssh://git@xxxx.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@xxxx.git'
```

**Comment by andreas-tsu** [comment]
Using master with the same issue, downgrade to 1.0.2 binary, restart service and all commits were in the right place.

**Comment by lunny** [comment]
#1077 will fix this.

**Comment by lunny** [comment]
@dh-harald @andreas-tsu please help to confirm #1077 fixed your issue.

**Comment by lunny** [comment]
@geek1011 also please.

**Comment by pgaskin** [comment]
Yes, it did. I built it last night.

**Comment by lunny** [comment]
@geek1011 glad to hear that.

**Comment by bkleef** [comment]
Fixed on Postgres too!

**Comment by davidhq** [comment]
I'm still receiving this message ... using Gitea v1.3, installed with binary on debian.

Error msg:
` ! [remote rejected] master -> master (pre-receive hook declined)`

Is there any solution to this?

**Comment by lunny** [comment]
@davidhq any version of you and since this PR is very old(it's in v1.1 but now v1.3), please fire another issue if your problem isn't fixed after you upgraded.

**Comment by davidhq** [comment]
OK - https://github.com/go-gitea/gitea/issues/2952
