### ISSUE TITLE
PR Commit and Changed Files tab broken

### ISSUE THREAD

**Issue by xoxys** [go-gitea/gitea#10920]
- Gitea version (or commit ref): 1.11.4
- Operating system: CentOS 7
- Database (use `[x]`):
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite

## Description
After upgrading to v1.11.3 the tabs for `Commits` and `Changed Files` are no longer accessible after a PR was merged.

## Screenshot
![grafik](https://user-images.githubusercontent.com/3391958/78170660-93437280-7453-11ea-9c9a-cafb6cdaf825.png)

**Comment by zeripath** [comment]
Hi we've already fixed this with PR #10909. See #10766  

There will be a migration that fixes these and other older problems in 1.12 - the code is in #10786

**Comment by zeripath** [comment]
Please upgrade to 1.14 where the issue is fixed.

**Comment by xoxys** [comment]
@zeripath I am already on 1.11.4 as written in my first post and it is still broken for an existing PR as you could see in the screenshot

**Comment by xoxys** [comment]
Ok, it's fixed for new PR's but old broken PR's stay broken currently, right?

**Comment by zeripath** [comment]
Yup sorry about that they'll get fixed when the migrations in 1.12 run but you can manually fix.

**Comment by xoxys** [comment]
No worries. I've just misunderstood that point 🙂
