### ISSUE TITLE
cannot see release drafts

### ISSUE THREAD

**Issue by sfinke0** [go-gitea/gitea#1387]
- Gitea version (or commit ref): 1.1.0+75-g6a451a2b
- Git version: 2.9.3
- Operating system: does not matter
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [x] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description
When I **draft** a release, I cannot see it in the release overview and therefore cannot edit my draft.
Can you please verify this?

1. create repo
2. commit a file
3. go to release tab in gitea
4. enter release information
5. press the "save draft" button
6. nothing appears in release overview

**Comment by lunny** [comment]
Which is your `git` version? I think this issue is duplicated with #1133 and resolved by go-gitea/git#48.

**Comment by sfnke** [comment]
Hmm I don't think this is a duplicate since this is still reproducable with https://try.gitea.io which is currently at `66c803f `

I can see my published releases, but I **cannot** see my release drafts. (e.g. https://try.gitea.io/carazzim0/my-first-repo has one release and like at least 2 drafts which I cannot see)

If you need more information, let me know.

**Comment by viktike** [comment]
Same here, draft releases disappearing. The only clue it did something, is that I cannot use the same release name again.
Git version on gitea server: 2.7.4

**Comment by lunny** [comment]
@carazzim0 please confirm #1854 fix this issue.

**Comment by sfnke** [comment]
@lunny can confirm this issue is resolved, thanks alot!
