### ISSUE TITLE
Cannot find package "context".

### ISSUE THREAD

**Issue by Lourens-Rich** [go-gitea/gitea#1491]
Hello. I tryed to build gitea, but it failed. 
```
git@Ubuntu1604x64:~/go/src/code.gitea.io/gitea$ go build -v
vendor/code.gitea.io/git/command.go:9:2: cannot find package "context" in any of:
	/home/git/go/src/code.gitea.io/gitea/vendor/context (vendor tree)
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/home/git/go/src/context (from $GOPATH)
```
I think it's associated with this commit: https://github.com/go-gitea/git/commit/135704d70ee8dddec363e80f3235092493fea2c2

Gitea version: d409d3a Go: go1.6.2 linux/amd64

**Comment by sapk** [comment]
I think that context lib was added in Go 1.7

**Comment by sapk** [comment]
It has moved to standards libs in Go1.7 to be exact. https://golang.org/doc/go1.7#context

Upgrade your go installation if possible.

**Comment by strk** [comment]
This is a regression. Dropping support for Go 1.6 should be an explicit choice if any. Did anyone bisect to find the offending commit ?

**Comment by sapk** [comment]
@strk The commit is in the issue description.

**Comment by Lourens-Rich** [comment]
I can close this issue if you promise to change build requirements for a next Gitea release.

**Comment by bkcsoft** [comment]
Please keep it open until a fix has been merged :)

**Comment by couling** [comment]
FYI ubuntu 16.04 LTS still does not have support for go 1.7.  Think carefully before dropping support for 1.6.

**Comment by lunny** [comment]
Maybe use `golang.org/x/net/context` until ubuntu supported go1.7?

**Comment by 4oo4** [comment]
~~Any update on this? I was super excited to find out that Gitea existed and install it until I ran into this while building it.~~

I realized now I was just being super lazy, someone made a PPA for a newer go version. There are a few out there but this appears to be the most up to date:

https://launchpad.net/~gophers/+archive/ubuntu/archive

**Comment by cez81** [comment]
@4oo4 What OS?

For Ubuntu 16.04 there is https://packages.ubuntu.com/xenial-backports/golang-1.9

Edit:: Could probably close this issue now as Go 1.8 is required.

**Comment by 4oo4** [comment]
@cez81 Yeah, Ubuntu 16.04. The package I found has a newer go 1.9 version than the backports one you linked to.
