### ISSUE TITLE
The problem in the work of the SSH server after migration and relocation

### ISSUE THREAD

**Issue by visteras** [go-gitea/gitea#15788]
As I understand it, this is a compound problem, parts of which have already been discussed in another Issues

- Gitea version (or commit ref): 1.14.1
- Git version: client - git version 2.30.1.windows.1, server - actual for 1.14.1 docker version
- Operating system: Kubernetes(from mail.ru), official helm chart
- Database (use `[x]`):
  - [x] PostgreSQL
  - [x] MySQL(MariaDB)
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [x] No

## Description

A small preface. Step by step
1) I used MariaDB and Docker on my personal server
2) I decided to switch to Mail Kubernetes
3) I used gitea [dump](https://docs.gitea.io/en-us/backup-and-restore/#backup-command-dump) (for postgres) and gitea [restore](https://docs.gitea.io/en-us/backup-and-restore/#restore-command-restore) 
4) In PostgreSQL, I had to update the version table and manually fix the user records.
5) I was unable to add the organization due to the wrong sequence in the users table, I had to fix it manually and I don’t know if it will happen again in other tables
6) ssh didn't work after running gitea on kubernetes (I used ingress nginx tcp (22:gitea-ssh:PROXY))
7) as a way to fix it turned out to be deleted and added with a new ssh key

P.S. the administrator is always created in helm hart. there is a default username and password
P.P.S. Something needs to be done to transfer data from the archive to the PV, because my 1.5 GB took about 2 hours (!) i had to use `kubectl cp`, this can really be a problem for larger owners.

In general, I solved my problems, but since I believe that there is something to fix here, I share the problems and their solutions with the community. If there are people willing to fix it, I think it will be good for both new versions and new users.

I'm glad that it turned out to be "simple enough", but I don't like the fact that such a recovery is possible at all. I think there is some kind of bug here.

Additional Information:
result from ssh connect or git clone:
```
...Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
And i see try connect in pod log:
```
Received disconnect from 10.100.64.23 port 59462:3: com.jcraft.jsch.JSchException: Auth fail [preauth]
Disconnected from authenticating user git 10.100.64.23 port 59462 [preauth]
Could not load host certificate "/data/ssh/ssh_host_ed25519_cert": No such file or directory
Could not load host certificate "/data/ssh/ssh_host_rsa_cert": No such file or directory
Could not load host certificate "/data/ssh/ssh_host_ecdsa_cert": No such file or directory
Could not load host certificate "/data/ssh/ssh_host_dsa_cert": No such file or directory
kex_exchange_identification: Connection closed by remote host
```
config gitea:
```yaml
...
    server:
      APP_DATA_PATH: /data/gitea
      SSH_DOMAIN: git.domain
      DISABLE_SSH: false
      START_SSH_SERVER: false
      # SSH_LISTEN_PORT: 2200
      SSH_PORT: 22
      DOMAIN: git.domain
      OFFLINE_MODE: false
...
```
values image:
```yaml
image:
  repository: gitea/gitea
  tag: 1.14.1
  pullPolicy: Always
  rootless: false
```

**Comment by zeripath** [comment]
you likely need to regenerate hooks - go to the admin pages and click on resynchronize pre-receive, update and post-recevie hooks of all repositories.

![resync](https://user-images.githubusercontent.com/1824502/117566118-ac820e00-b0ac-11eb-8017-0fce695cc644.png)

**Comment by noerw** [comment]
Assuming this is resolved, please reopen if the proposed solution didn't work

**Comment by volker-raschek** [comment]
I have the same issue. Resynchronize the pre-receive, update and post-receive hooks does not solve the problem.

**Comment by zeripath** [comment]
Please do not comment directly on closed issues. Open a new one.
