### ISSUE TITLE
view STL files 2

### ISSUE THREAD

**Issue by raidenlal** [go-gitea/gitea#16352]
- Gitea version (or commit ref): 1.15.0+dev-541-g5bb97a12d
- Git version: UI related
- Operating system: docker container using gitea/gitea:latest
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [X] No
- Log gist:

## Description
Continuing discussion from previous issue: https://github.com/go-gitea/gitea/issues/5979
This would be really nice thing to have out of box, but okay I have followed proposed solution: "I will close this issue as it can be setup by many ways and **at least one is in docs**."

I looked at the docu:
https://docs.gitea.io/en-us/customizing-gitea/#example-stl-preview
Link there to https://jinjunho.github.io/Madeleine.js/ is no longer working, so google found some other repo of the project: https://github.com/beige90/Madeleine.js However last commit there is 7 years ago, feels abandoned.

So I have mapped required directories from the container to host machine and put required stuff according to the docs:
```
bash-5.1# pwd
/usr/share/git-core/public/Madeleine.js
bash-5.1# ls
LICENSE    README.md  css        examples   images     models     src
```
And the template:
```
bash-5.1# pwd
/usr/share/git-core/templates/custom
bash-5.1# ls
footer.tmpl
bash-5.1# cat footer.tmpl 
<script>
  function lS(src) {
    return new Promise(function (resolve, reject) {
      let s = document.createElement("script");
      s.src = src;
      s.addEventListener("load", () => {
        resolve();
      });
      document.body.appendChild(s);
    });
  }

  if ($('.view-raw>a[href$=".stl" i]').length) {
    $("body").append(
      '<link href="/Madeleine.js/src/css/Madeleine.css" rel="stylesheet">'
    );
    Promise.all([
      lS("/Madeleine.js/src/lib/stats.js"),
      lS("/Madeleine.js/src/lib/detector.js"),
      lS("/Madeleine.js/src/lib/three.min.js"),
      lS("/Madeleine.js/src/Madeleine.js"),
    ]).then(function () {
      $(".view-raw")
        .attr("id", "view-raw")
        .attr("style", "padding: 0;margin-bottom: -10px;");
      new Madeleine({
        target: "view-raw",
        data: $('.view-raw>a[href$=".stl" i]').attr("href"),
        path: "/Madeleine.js/src",
      });
      $('.view-raw>a[href$=".stl"]').remove();
    });
  }
</script>
```
And result is:
![image](https://user-images.githubusercontent.com/53146816/124613060-25b29d00-de73-11eb-878d-60d175f123bf.png)

Any ideas?

**Comment by noerw** [comment]
I didn't try this myself, but I'd check the network tab in your browsers developer tools, and see if all requests could be resolved, and what errors are visible in the console.

It could also be that the JS just doesn't match how gitea renders the page anymore.
In any case, it would be nice if you send a PR updating the docs, once you get it to work :)

**Comment by raidenlal** [comment]
Console does not contain any errors and there are no failed requests. It looks like the new template is just being completely ignored - thats why I did provide the complete file listings in the issue - in case some file was misplaced or something.

**Comment by noerw** [comment]
Ah, I didn't check the paths too thoroughly.
Are you sure `/usr/share/git-core` is your gitea custom path? If it's your base gitea working directory, this would be the right path:

```diff
- /usr/share/git-core/templates/custom/
- /usr/share/git-core/public/
+ /usr/share/git-core/custom/templates/custom/
+ /usr/share/git-core/custom/public/
```
If you're using the default dockerfile, the base path is `/data/gitea`. → So `/data/gitea/custom/templates/custom` etc

**Comment by raidenlal** [comment]
I am using default docker image. So I have tried to put it into /data, like so:
```
bash-5.1# ls -la
total 0
drwxrwxrwx    1 root     root           512 Jul 10 10:30 .
drwxr-xr-x    1 git      git            512 Jul 10 10:30 ..
drwxrwxrwx    1 root     root           512 Jul 10 10:30 public
drwxrwxrwx    1 root     root           512 Jul 10 10:29 templates
bash-5.1# ls -la public/
total 0
drwxrwxrwx    1 root     root           512 Jul 10 10:30 .
drwxrwxrwx    1 root     root           512 Jul 10 10:30 ..
drwxrwxrwx    1 root     root           512 Jul 10 10:30 Madeleine.js
bash-5.1# ls -la templates/custom/
total 4
drwxrwxrwx    1 root     root           512 Jul 10 10:29 .
drwxrwxrwx    1 root     root           512 Jul 10 10:29 ..
-rwxrwxrwx    1 root     root          1018 Jul  6 13:45 footer.tmpl
bash-5.1# pwd
/data/gitea/custom
```
but this is not working either.

**Comment by raidenlal** [comment]
I have also tried the other way:
```
bash-5.1# ls /usr/share/git-core/custom/templates/custom/
footer.tmpl
bash-5.1# ls /usr/share/git-core/custom/public/Madeleine.js
LICENSE    README.md  css        examples   images     models     src
```

**Comment by noerw** [comment]
If you're using the official docker image, `/data/gitea/custom` is the way to go. I don't see how gitea should know about your `/usr/share/git-core` path.

**Comment by raidenlal** [comment]
Yes on the last comment I have shown that I tried to put it in the /data/gitea/custom:
```
bash-5.1# cd /data/gitea/custom
bash-5.1# ls
public     templates
bash-5.1# ls public/
Madeleine.js
bash-5.1# ls templates/
custom
bash-5.1# ls templates/custom/
footer.tmpl
bash-5.1# 
```
but no STL viewer is still showing.

**Comment by zeripath** [comment]
Ah you've been affected by the changes in #15219

I've just pushed up some updated documentation.

Files in custom/public are now mounted within `assets/` not `/` so you need to update your templates to account for that.

**Comment by raidenlal** [comment]
Thanks for the note. I've adjusted my folder structure, but the wording the once using "custom/public" and then referencing "assets" and "/" without mentioning "custom/public" seems confusing.
Now I have:
```
bash-5.1# ls -la /data/gitea/custom/public/assets/
total 0
drwxrwxrwx    1 root     root           512 Jul 15 22:12 .
drwxrwxrwx    1 root     root           512 Jul 15 22:12 ..
drwxrwxrwx    1 root     root           512 Jul 10 10:30 Madeleine.js
bash-5.1# ls -la /data/gitea/custom/templates/custom/
total 4
drwxrwxrwx    1 root     root           512 Jul 10 10:29 .
drwxrwxrwx    1 root     root           512 Jul 10 10:29 ..
-rwxrwxrwx    1 root     root          1018 Jul  6 13:45 footer.tmpl
```
The thing is that the javascript library is not even trying to be downloaded byt the footer template - it seems the root cause is template not working. I don't see any failed http requests in the browser developer console. Or maybe my assumptions are totally wrong - anyways - STL still not showing.

Could you, please, doublecheck my folder structure?

**Comment by raidenlal** [comment]
Ooooh I get it.
Template is referencing
```
    $("body").append(
      '<link href="/Madeleine.js/src/css/Madeleine.css" rel="stylesheet">'
    );
```
which should be `/assets/Madeleine.js/src/css/Madeleine.css`?

I've reverted folder structure to:
```
ash-5.1# ls -l /data/gitea/custom/public/
total 0
drwxrwxrwx    1 root     root           512 Jul 10 10:30 Madeleine.js
bash-5.1# ls -l /data/gitea/custom/templates/custom/
total 4
-rwxrwxrwx    1 root     root          1018 Jul  6 13:45 footer.tmpl
```
However STL still not showing as if template was ignored. Also BASE_URL/assets/Madeleine.js/src/css/Madeleine.css results in 404 so it seems something is totally wrong.
