### ISSUE TITLE
[Bug Report] Relative links in markdown

### ISSUE THREAD

**Issue by renaissance14** [go-gitea/gitea#18592]
# Introduction

When using relative links in markdown files you have to use either `./file.md` or `file.md`. When trying to use `/file.md` you will get redirected to the root of the gitea instance.

# Example

https://try.gitea.io/schorsch/relative-links-in-markdown

![image](https://user-images.githubusercontent.com/97637661/152493333-cf54bbe9-0ab1-4fbc-87ce-8637b62ce7d9.png)

# Proposal

Change `/file.md` from directing to the web root to the project root

# Credits

The bug was discovered by the codeberg user [ivan-paleo](https://codeberg.org/ivan-paleo). For further information have a look at the issue at codeberg: https://codeberg.org/Codeberg/Community/issues/252

**Comment by zeripath** [comment]
This was fixed at some point and something has caused a regression!!

**Comment by zeripath** [comment]
Yes this was fixed in #15088

This is particularly irritating as there was even a test created to prevent this from happening YET AGAIN

**Comment by zeripath** [comment]
Let's just go through this again.

The base url for an image link rendered in a file GH is:

`/owner/repo/blob/branch/path/to/file/`

Relative links may traverse out of the repo i.e. if a file that is in `/` of `owner/repo` on the default branch `master` has a link:

`../../../../owner2/repo2` 

then it would like to `/owner2/repo2` directly.

Links that start with a `/` e.g. `/../../../owner2/repo2` do not traverse out of the repo.

---

I'll do some more test cases in pathological and properly add tests to gitea to prevent this from happening yet again.

**Comment by zeripath** [comment]
OK I guess we need the following (this is for a gitea mounted on a suburl /gitea):

|name | input | file | fileInDir | wiki | issue|
|--------|--------|------|------------|-------|-----|
|samedir | file | /gitea/gogits/gogs/src/branch/master/file | /gitea/gogits/gogs/src/branch/master/subdir/file | /gitea/gogits/gogs/wiki/file | /gitea/gogits/gogs/issues/file|
|childir | subdir/file | /gitea/gogits/gogs/src/branch/master/subdir/file | /gitea/gogits/gogs/src/branch/master/subdir/subdir/file | /gitea/gogits/gogs/wiki/subdir/file | /gitea/gogits/gogs/issues/subdir/file|
|/file | /file | /gitea/gogits/gogs/src/branch/master/file | /gitea/gogits/gogs/src/branch/master/file | /gitea/file | /gitea/file|
|../file | ../file | /gitea/gogits/gogs/src/branch/file | /gitea/gogits/gogs/src/branch/master/file | /gitea/gogits/gogs/file | /gitea/gogits/gogs/file|
|/../file | /../file | /gitea/gogits/gogs/src/branch/file | /gitea/gogits/gogs/src/branch/file | /gitea/file | /gitea/file|
|../../file | ../../file | /gitea/gogits/gogs/src/file | /gitea/gogits/gogs/src/branch/file | /gitea/gogits/file | /gitea/gogits/file|
|/../../file | /../../file | /gitea/gogits/gogs/src/file | /gitea/gogits/gogs/src/file | /gitea/file | /gitea/file|
|../../../file | ../../../file | /gitea/gogits/gogs/file | /gitea/gogits/gogs/src/file | /gitea/file | /gitea/file|
|../../../../file | ../../../../file | /gitea/gogits/file | /gitea/gogits/gogs/file | /gitea/file | /gitea/file|
|../../../../../file | ../../../../../file | /gitea/file | /gitea/gogits/file | /gitea/file | /gitea/file|
|../../../../../../file | ../../../../../../file | /gitea/file | /gitea/file | /gitea/file | /gitea/file|
|../../../../../../../file | ../../../../../../../file | /gitea/file | /gitea/file | /gitea/file | /gitea/file|

One slight problem is that this this is still not github compatible - githubs blob urls are:

https://github.com/zeripath/pathological/blob/master/README.md

Whereas the equivalent in Gitea:

https://try.gitea.io/arandomer/pathological/src/branch/master/README.md

So we're already slightly incompatible.

However, the `/` behaviour would be the least we should do.

**Comment by zeripath** [comment]
<details>
<summary>TestCase to add to modules/markup/markdown/markdown_test.go</summary>

```go
func TestRender_RelativeLinks(t *testing.T) {
	setting.AppURL = "https://localhost:3000/gitea/"
	setting.AppSubURL = "/gitea"

	testcases := []struct {
		name              string
		input             string
		expectedFile      string
		expectedFileInDir string
		expectedWiki      string
		expectedIssue     string
	}{
		{
			name:              "samedir",
			input:             "file",
			expectedFile:      "/gitea/gogits/gogs/src/branch/master/file",
			expectedFileInDir: "/gitea/gogits/gogs/src/branch/master/subdir/file",
			expectedWiki:      "/gitea/gogits/gogs/wiki/file",
			expectedIssue:     "/gitea/gogits/gogs/issues/file",
		},
		{
			name:              "childir",
			input:             "subdir/file",
			expectedFile:      "/gitea/gogits/gogs/src/branch/master/subdir/file",
			expectedFileInDir: "/gitea/gogits/gogs/src/branch/master/subdir/subdir/file",
			expectedWiki:      "/gitea/gogits/gogs/wiki/subdir/file",
			expectedIssue:     "/gitea/gogits/gogs/issues/subdir/file",
		},
		{
			name:              "/file",
			input:             "/file",
			expectedFile:      "/gitea/gogits/gogs/src/branch/master/file",
			expectedFileInDir: "/gitea/gogits/gogs/src/branch/master/file",
			expectedWiki:      "/gitea/file",
			expectedIssue:     "/gitea/file",
		},
		{
			name:              "../file",
			input:             "../file",
			expectedFile:      "/gitea/gogits/gogs/src/branch/file",
			expectedFileInDir: "/gitea/gogits/gogs/src/branch/master/file",
			expectedWiki:      "/gitea/gogits/gogs/file",
			expectedIssue:     "/gitea/gogits/gogs/file",
		},
		{
			name:              "/../file",
			input:             "/../file",
			expectedFile:      "/gitea/gogits/gogs/src/branch/file",
			expectedFileInDir: "/gitea/gogits/gogs/src/branch/file",
			expectedWiki:      "/gitea/file",
			expectedIssue:     "/gitea/file",
		},
		{
			name:              "../../file",
			input:             "../../file",
			expectedFile:      "/gitea/gogits/gogs/src/file",
			expectedFileInDir: "/gitea/gogits/gogs/src/branch/file",
			expectedWiki:      "/gitea/gogits/file",
			expectedIssue:     "/gitea/gogits/file",
		},
		{
			name:              "/../../file",
			input:             "/../../file",
			expectedFile:      "/gitea/gogits/gogs/src/file",
			expectedFileInDir: "/gitea/gogits/gogs/src/file",
			expectedWiki:      "/gitea/file",
			expectedIssue:     "/gitea/file",
		},
		{
			name:              "../../../file",
			input:             "../../../file",
			expectedFile:      "/gitea/gogits/gogs/file",
			expectedFileInDir: "/gitea/gogits/gogs/src/file",
			expectedWiki:      "/gitea/file",
			expectedIssue:     "/gitea/file",
		},
		{
			name:              "../../../../file",
			input:             "../../../../file",
			expectedFile:      "/gitea/gogits/file",
			expectedFileInDir: "/gitea/gogits/gogs/file",
			expectedWiki:      "/gitea/file",
			expectedIssue:     "/gitea/file",
		},
		{
			name:              "../../../../../file",
			input:             "../../../../../file",
			expectedFile:      "/gitea/file",
			expectedFileInDir: "/gitea/gogits/file",
			expectedWiki:      "/gitea/file",
			expectedIssue:     "/gitea/file",
		},
		{
			name:              "../../../../../../file",
			input:             "../../../../../../file",
			expectedFile:      "/gitea/file",
			expectedFileInDir: "/gitea/file",
			expectedWiki:      "/gitea/file",
			expectedIssue:     "/gitea/file",
		},
		{
			name:              "../../../../../../../file",
			input:             "../../../../../../../file",
			expectedFile:      "/gitea/file",
			expectedFileInDir: "/gitea/file",
			expectedWiki:      "/gitea/file",
			expectedIssue:     "/gitea/file",
		},
	}

	for _, testcase := range testcases {
		t.Run(testcase.name, func(t *testing.T) {
			t.Run("file", func(t *testing.T) {
				buffer, err := RenderString(&markup.RenderContext{
					URLPrefix: setting.AppSubURL + "/" + Repo + "/src/branch/master/",
					Filename:  "test.md",
					Metas: map[string]string{
						"user":     "gogits",
						"repo":     "gogs",
						"repoPath": "../../../integrations/gitea-repositories-meta/user13/repo11.git/",
					},
				}, "["+testcase.input+"]("+testcase.input+")")
				assert.NoError(t, err)
				assert.Equal(t, fmt.Sprintf("<p><a href=\"%s\" rel=\"nofollow\">%s</a></p>", testcase.expectedFile, testcase.input), strings.TrimSpace(buffer), "Incorrect file path")
			})
			t.Run("fileInDir", func(t *testing.T) {
				buffer, err := RenderString(&markup.RenderContext{
					URLPrefix: setting.AppSubURL + "/" + Repo + "/src/branch/master/subdir/",
					Filename:  "test.md",
					Metas: map[string]string{
						"user":     "gogits",
						"repo":     "gogs",
						"repoPath": "../../../integrations/gitea-repositories-meta/user13/repo11.git/",
					},
				}, "["+testcase.input+"]("+testcase.input+")")
				assert.NoError(t, err)
				assert.Equal(t, fmt.Sprintf("<p><a href=\"%s\" rel=\"nofollow\">%s</a></p>", testcase.expectedFileInDir, testcase.input), strings.TrimSpace(buffer), "Incorrect subdir file path")
			})
			t.Run("wiki", func(t *testing.T) {
				buffer, err := RenderString(&markup.RenderContext{
					URLPrefix: setting.AppSubURL + "/" + Repo,
					IsWiki:    true,
					Metas: map[string]string{
						"user":     "gogits",
						"repo":     "gogs",
						"repoPath": "../../../integrations/gitea-repositories-meta/user13/repo11.git/",
					},
				}, "["+testcase.input+"]("+testcase.input+")")
				assert.NoError(t, err)
				assert.Equal(t, fmt.Sprintf("<p><a href=\"%s\" rel=\"nofollow\">%s</a></p>", testcase.expectedWiki, testcase.input), strings.TrimSpace(buffer), "Incorrect wiki path")
			})
			t.Run("comment", func(t *testing.T) {
				buffer, err := RenderString(&markup.RenderContext{
					URLPrefix: setting.AppSubURL + "/" + Repo + "/issues/",
					Metas: map[string]string{
						"user":     "gogits",
						"repo":     "gogs",
						"repoPath": "../../../integrations/gitea-repositories-meta/user13/repo11.git/",
						"mode":     "comment",
					},
				}, "["+testcase.input+"]("+testcase.input+")")
				assert.NoError(t, err)
				assert.Equal(t, fmt.Sprintf("<p><a href=\"%s\" rel=\"nofollow\">%s</a></p>", testcase.expectedIssue, testcase.input), strings.TrimSpace(buffer), "Incorrect issue path")
			})
		})
	}
}
```

</details>

**Comment by charles-997** [comment]
Has there been any progress on this bug? This seems like a reasonably important feature-breaking bug!
I was surprised to see that my relative links in existing repositories do not function properly in Gitea.

**Comment by xbreaker** [comment]
Same problem with using HTML A tag in markdown with relative file name

Steps:
1. Create markdown file with HTML tag A and link to local file (for example, <a href="readme.md>readme</a>
2. Save file, link will lost current path, if you viewing branch link will be `/repo/src/branch/file.md` instead of  `/repo/src/branch/main/file.md`

Demo: https://try.gitea.io/aybe/markdown-branch/

**Comment by lunny** [comment]
From https://try.gitea.io/aybe/markdown-branch/ , only relative link from a tag is wrong. Maybe it's accepted?

**Comment by ell1e** [comment]
I just ran into this, sadly it seems to break almost all links in my documentation so this is a really high impact bug in my opinion. Especially since with the GitHub mirror it works fine.

Here's a demo file with a link that should work but it doesn't:

https://try.gitea.io/blablablablab/BlaTest/src/branch/main/A%20B/outsidelink.md

(The big bold **(test link)** is what you want to click. Expected behavior is that it gets you to the target file in the repository root, actual behavior is some nonsensical location.)

**Comment by CaiCandong** [comment]
Duplicate of #25632
Maybe fixed by #26774

**Comment by vilunov** [comment]
In original post it is said that relative links such as `[text](file.md)` or `[text](./file.md)` resolve correctly, but absolute ones do not. This is not my experience with Gitea 1.21.4. [Example](https://git.vilunov.me/lavina/lavina/src/branch/main/readme.md)

I expect that a link such as `[Project structure](crates/readme.md)` in the project readme should be resolved to `example.com/org/repo/src/branch/main/crates/readme.md`, instead it is resolved to `example.com/org/repo/crates/readme.md`, making it pretty much useless, as it is always broken.

**Comment by vilunov** [comment]
The issue above seems to be a regression between 1.20.5 and 1.21.4

**Comment by vilunov** [comment]
@KN4CK3R sorry, pinging for visibility since you made the MR and you seem to be responsible for that area.

**Comment by vilunov** [comment]
Thanks, sorry for panicking. Relative links work again, but the absolute ones are still broken.

A link such as `/docs/running.md` will be rendered as it is in html and will lead to `localhost:3000/docs/running.md`

![image](https://github.com/go-gitea/gitea/assets/16502164/7ad4a542-9a72-49ae-be40-a3d8c404b5d3)
![image](https://github.com/go-gitea/gitea/assets/16502164/de044a39-10e9-46f0-b3b0-c12a04abe276)

**Comment by KN4CK3R** [comment]
Ok, that's not a regression of my PR 🎉 Gitea always rendered them like that. It's debatable what the root is for absolute links. Even Github is inconsistent with the links.

Inside issue:
[A](A)

[/A](/A)

[../A](../A)

[../../A](../../A)

[../../../A](../../../A)

[../../../../A](../../../../A)

[../../../../../A](../../../../../A)

[../../../../../../A](../../../../../A)

[/../A](/../A)

Inside repo:
https://github.com/KN4CK3R/Test/blob/4398ccfc630b9b438421ca7e16c60de0538127cd/README.md

---

A fix would be to strip the `/` prefix for links too:
https://github.com/go-gitea/gitea/blob/3e8414179c3f3e8a12d3a66fdf32c144f941f5c3/modules/markup/markdown/goldmark.go#L148
```diff
- link = []byte(giteautil.URLJoin(base, string(link)))
+ link = []byte(giteautil.URLJoin(base, strings.TrimLeft(string(link), "/")))
```

**Comment by vilunov** [comment]
GitHub is not very consistent even when it comes to rendering `README.md` as a repo front page or as an individual file.

Example:
link in the first footnote at the end of `README.md`
https://github.com/ratijas/kdesrc-build-sublime -- renders as `https://github.com/ratijas/plugins/gen_conf_options.py`
https://github.com/ratijas/kdesrc-build-sublime/blob/master/README.md -- renders as `https://github.com/ratijas/kdesrc-build-sublime/blob/master/plugins/gen_conf_options.py`

It really is tricky

**Comment by ell1e** [comment]
@vilunov the first one seems more like a bug, doesn't it? usually in almost all places on GitHub it behaves like the 2nd example. maybe they just forgot about this corner case of footnotes in the one location, that feels like the most likely.

on gitea, sadly it still doesn't seem to work for links starting with `/` ever, not even in corner cases, see ["Broken Example 2" here](https://try.gitea.io/blablablablab/BlaTest/src/branch/main/linktest.md#broken-example-2). this makes writing documentation where individual pages can be moved around inside the documentation folder without all their links to other files breaking quite difficult. so i hope this can be fixed eventually.

**Comment by levicki** [comment]
I am having (a variation of?) this problem on the latest version of Gitea (served at root, not at sub-path) &mdash; For example I write:
```
see [README](README.md)
```
In the Release description field and the link is replaced with:
```
https://example.com:3000/my_organization/my_project/README.md
```
And results in 404 error when clicked. Actual README.md link in the source tree shows as:
```
https://example.com:3000/my_organization/my_project/src/branch/master/README.md
```
I don't think either would be correct for Releases though &mdash; it should link to specific tagged release version of the file.

**Comment by neutronstriker** [comment]
Is this bug resolved now, I am facing the same issue with version 1.21.4.
-Thanks.

**Comment by wxiaoguang** [comment]
It is not really fixed. Because the "absolute path" link handling is quite tricky and ambiguous.

And, if we change this behavior, it is a "breaking" change and will make existing "absolute-path" links broken.

**Comment by neutronstriker** [comment]
> It is not really fixed. Because the "absolute path" link (starting with a slash `/xxxx`) handling is quite tricky and ambiguous.
> 
> And, if we change this behavior, it is a "breaking" change and will make all existing "absolute-path" links broken.

Which means we need to use /src/branch/main/ as a prefix right?

**Comment by wxiaoguang** [comment]
> Which means we need to use /src/branch/main/ as a prefix right?

Or use relative path like `../../foo/bar`.

----

Maybe I could take a try in 1.23 to "fix/improve" the path handling, but I can't promise at the moment.

**Comment by neutronstriker** [comment]
I just updated my installation to 1.22.0 and my issue got resolved, my issue was the 1st one referenced in comment https://github.com/go-gitea/gitea/issues/18592#issuecomment-1030591957

**Comment by wxiaoguang** [comment]
> I moved recently to Forgejo, based on Gitea, and works fine. Even MD header URL links works fine, which I think is not the same with Gitea.

There are some different path problems, some have been fixed, while some are still not.

Forgejo is still largely based on Gitea's work, but they skipped some Gitea's commits (even some are security related) so I guess it couldn't be more complete than Gitea.

**Comment by wxiaoguang** [comment]
Made some tests on GitHub, I think we could just copy the behavior (and mark it as breaking)

https://github.com/wxiaoguang/playground/blob/44cc37ef49eb827345dd0d9d510b319f81f63f16/test.md

https://github.com/wxiaoguang/playground/blob/6bd6f1da05afc914abf452628d90c90b71093820/dir/test.md

**Comment by levicki** [comment]
> But not sure whether we should 100% follow it ........

I vote for using the same logic as GitHub &mdash; that makes it easier to have both private Gitea and public GitHub repo with correct links in both.

Also please make sure that it works not just in issues and comments but in releases as well.

**Comment by ell1e** [comment]
> I moved recently to Forgejo, based on Gitea, and works fine.

In Foregjo 7.0.0 this seems **not** fixed, and linking e.g. `/docs/start.md` inside a repository's main folder inside a `README.md`, won't actually link to `https://instance.org/user/repo/src/branch/main/docs/start.md` as it probably should. At least as far as I can tell.

**Comment by wxiaoguang** [comment]
> > I moved recently to Forgejo, based on Gitea, and works fine.
> 
> In Foregjo 7.0.0 this seems **not** fixed, and linking e.g. `/docs/start.md` inside a repository's main folder inside a `README.md`, won't actually link to `https://instance.org/user/repo/src/branch/main/docs/start.md` as it probably should. At least as far as I can tell.

Actually they missed many bug fixes or improvements, because they hard-forked and skipped many commits.

**Comment by delvh** [comment]
:face_exhaling: 
guys, I've marked the comments above as off-topic.
They have nothing to do with this issue or Gitea.
AFAIK, Forgejo hardforked some months ago and has diverged since.
as such, the two projects can no longer be seen as equal.
If you encounter issues with Forgejo, please discuss it with them instead of in the Gitea issue tracker.
I'll hide my own comment as well to not disturb others.

**Comment by busslina** [comment]
https://forgejo.org/compare-to-gitea/
https://forgejo.org/compare-to-gitea/#better-security

**Comment by wxiaoguang** [comment]
> https://forgejo.org/compare-to-gitea/ https://forgejo.org/compare-to-gitea/#better-security
> 
> I can be a bridge between both parts because I have no problem with any of both :) haha

Then you could tell them they have some XSS in some pages, but not in Gitea.

**Comment by ApplePie420** [comment]
v1.21.4, bare metal installation, server as root of subdomain. I have the same problem, e.g.

In `README.md` I have

```md
[Schematics available in the docs folder](docs/schematics.pdf)
```

And it doesn't work. Full path to the file is `src/branch/main/docs/schematics.pdf`. This is extremely stupid, not only introduces way more text to typo, but just is not intuitive and transferable to other git UIs. I assume this hasn't been resolved yet.

**Comment by lunny** [comment]
> v1.21.4, bare metal installation, server as root of subdomain. I have the same problem, e.g.
> 
> In `README.md` I have
> 
> ```
> [Schematics available in the docs folder](docs/schematics.pdf)
> ```
> 
> And it doesn't work. Full path to the file is `src/branch/main/docs/schematics.pdf`. This is extremely stupid, not only introduces way more text to typo, but just is not intuitive and transferable to other git UIs. I assume this hasn't been resolved yet.

Can you upgrade to v1.22.3 to try it again?

**Comment by wxiaoguang** [comment]
> Can you upgrade to v1.22.3 to try it again?

It hasn't been improved yet. I am still working on some markdown refactorings. If I complete I would tell here.

**Comment by wxiaoguang** [comment]
Refactor markup render system #32612 

Almost done, this PR will fix most problems.

**Comment by wxiaoguang** [comment]
> v1.21.4, bare metal installation, server as root of subdomain. I have the same problem, e.g.
> 
> In `README.md` I have
> 
> ```
> [Schematics available in the docs folder](docs/schematics.pdf)
> ```
> 
> And it doesn't work. Full path to the file is `src/branch/main/docs/schematics.pdf`. This is extremely stupid, not only introduces way more text to typo, but just is not intuitive and transferable to other git UIs. I assume this hasn't been resolved yet.

Hi  ApplePie420 , I have tested your markdown in 1.22, it seems that 1.22 could render that relative path correctly (something should have been fixed there). Would you like to upgrade to 1.22 and take a try? No need to wait for 1.23.

Screenshot:

<details>

![image](https://github.com/user-attachments/assets/a306fb18-b3a9-46d0-987c-77371a277ee1)

</details>

If anything doesn't work as expected, please provide some reproducible examples. Thank you.

**Comment by ell1e** [comment]
https://demo.gitea.com/ell1e/linktest/src/branch/main/README.md This example suggests relative links with no trailing slash work, but relative links *with* trailing slash to link files relative to the base of the file tree still don't work (which they do on GitHub). I hope this is helpful.

**Comment by wxiaoguang** [comment]
> https://demo.gitea.com/ell1e/linktest/src/branch/main/README.md This example suggests relative links with no trailing slash work, but relative links _with_ trailing slash to link to files relative to the root of the file tree still don't work (which they do on GitHub). I hope this is helpful.

Thank you, that's another problem and will be fixed in 1.23 (see my PR  #32612)

I think it works as expected now, feel free to try that PR 🙏

![image](https://github.com/user-attachments/assets/16ba2bfb-2aee-47b7-ab3b-c26c2c62e49a)

**Comment by wxiaoguang** [comment]
#32612 has been merged and the nightly build are ready (docker: main-nightly, binary: https://dl.gitea.com/gitea/main-nightly/ )

I think the "relative/absolute" path problem should have been fixed for most cases.

I have done my best to avoid regressions, if there is anything wrong, please let me know and I will fix bugs in first time.
