### ISSUE TITLE
Release can't be created on existing tag

### ISSUE THREAD

**Issue by ekaparulin** [go-gitea/gitea#21681]
### Description

If I create a release on an existing tag:

Releases -> Tag -> Tag name -> New release

Add title and click "Publish release" I get an error "Target branch does not exist."

Same with API:

```
curl -X 'POST' \
  'https://GITEA_HOST/api/v1/repos/ORG/REPO/releases' \
  -H 'accept: application/json' \
  -H 'authorization: Basic TOKEN' \
  -H 'Content-Type: application/json' \
  -d '{
  "body": "text3",
  "draft": false,
  "name": "RELEASE_NAME",
  "prerelease": false,
  "tag_name": "EXISTING_TAGE",
  "target_commitish": "SHA"
}'
{"message":"Release is has no Tag","url":"https://GITEA/api/swagger"}
```

I expected to be able to create a release from an existing tag. Tried versions 1.17.3, 1.18.0-rc0 and dev
Logs don't show any errors.

### Gitea Version

1.17.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

I am running Gitea as docker image (gitea/gitea).
Also reproduced on https://try.gitea.io/

### Database

MySQL

**Comment by KN4CK3R** [comment]
Works for me
![grafik](https://user-images.githubusercontent.com/1666336/200138243-f64f0cce-aaa0-497e-9d43-cc9c02cf9aee.png)

Tag 5.0.3 exists already.

**Comment by ekaparulin** [comment]
Hi @KN4CK3R ,

thank you for reviewing. Unfortunately I can't confirm it working as it works for you.

I tried to create a release as you did with empty "target_commitish", but I get the same error:

> 
> curl -X 'POST' 
>   'https://MYGIT/api/v1/repos/MYORG/MYREPO/releases' 
>   -H 'accept: application/json' 
>   -H 'authorization: Basic MYTOKEN' 
>   -H 'Content-Type: application/json' 
>   -d '{
>   "body": "text3",
>   "draft": false,
>   "name": "google-cloud-sdk-4",
>   "prerelease": false,
>   "tag_name": "google-cloud-sdk",
>   "target_commitish": ""
> }'

The result is: 

`{"message":"Release is has no Tag","url":"https://git.dev.mobileoperator.fi/api/swagger"}`

Also on https://try.gitea.io/ I have a repo https://try.gitea.io/eugen.kaparulin/release-bug-test with existing tag "tag2" and can reproduce the error:

- Through the UI:


<img width="1126" alt="UI" src="https://user-images.githubusercontent.com/19385659/200241988-14964cd6-0651-4b05-83be-ca3274561c60.png">

- Through API:

<img width="1151" alt="API" src="https://user-images.githubusercontent.com/19385659/200241999-74cabd79-ff5e-4a7c-ab51-cbe4eceab528.png">

**Comment by KN4CK3R** [comment]
Cloned your repo and it works for me:
![grafik](https://user-images.githubusercontent.com/1666336/200272017-76ccfeca-fa28-4f3d-9719-8c28e10401f8.png)

I think the problem is that you already have a release which uses `tag2`. If I try my request a second time with the same name I get the same (well written) error message.

**Comment by ekaparulin** [comment]
Hi @KN4CK3R ,

thank you for checking it.

To have a clean view on this, I added 2 commits to my repo and tagged them with tag4 and tag5 respectively:

<img width="952" alt="Screenshot 2022-11-07 at 11 39 50" src="https://user-images.githubusercontent.com/19385659/200277798-cbfe0df8-9400-44b3-9a2f-fb297d229518.png">

Then if I look at the tag list, there are 3 tags w/o releases (tag3, tag4, tag5):

<img width="879" alt="Screenshot 2022-11-07 at 11 41 42" src="https://user-images.githubusercontent.com/19385659/200278284-535b7bb5-9b21-4221-99be-6024ac1ae82b.png">

Now, just for the cleanliness of the experiment I attempt to create  a release on new commits  (tag4 and tag5):

Tag4:
<img width="869" alt="Screenshot 2022-11-07 at 11 45 26" src="https://user-images.githubusercontent.com/19385659/200279469-4a08674e-b9b4-4ef7-9007-44689a3403e9.png">

Tag5:
<img width="885" alt="Screenshot 2022-11-07 at 11 47 24" src="https://user-images.githubusercontent.com/19385659/200279514-45d5490c-cb0f-431e-81c2-c7b6d33a6685.png">

I didn't try the API, I assume the result will be the same.

**Comment by KN4CK3R** [comment]
Cloned it again and 🤷‍♂️ 
![tag](https://user-images.githubusercontent.com/1666336/200283373-d8ef45c8-5f58-4fb1-a53e-b0452e9e0465.gif)

**Comment by ekaparulin** [comment]
Hi @KN4CK3R ,

I have also recorded a short video:

![Recording 2022-11-07 at 12 40 52](https://user-images.githubusercontent.com/19385659/200290884-ec1cfe49-8a31-450d-8a0a-959283de5cc2.gif) 

I tried Chrome and Safari with same result.

**Comment by ekaparulin** [comment]
Hi @KN4CK3R,

I added you a collaborator to my repo: 

<img width="899" alt="Screenshot 2022-11-07 at 12 45 42" src="https://user-images.githubusercontent.com/19385659/200291576-83cc5a74-3a1f-421f-9f64-6f9929313a79.png">

Can you try to create releases directly on it?

**Comment by KN4CK3R** [comment]
I get the same error and found differences. But I don't know yet where they come from:

yours:
![grafik](https://user-images.githubusercontent.com/1666336/200304996-66ec6fdb-164b-4829-83b7-e869a3f4308d.png)

mine:
![grafik](https://user-images.githubusercontent.com/1666336/200305069-49786de0-d113-4715-b1b5-36b17fb19383.png)

POST request from your form:
![grafik](https://user-images.githubusercontent.com/1666336/200305187-12dc466d-1dda-4273-8458-bb3e9ccfdc75.png)

POST request from my form:
![grafik](https://user-images.githubusercontent.com/1666336/200305303-d2da20f9-cace-4edc-8611-56f4ff8e825c.png)

**Comment by ekaparulin** [comment]
Hi @KN4CK3R ,

excellent! 

I created the repo through the UI just before opening the issue. No sophisticated methods creating it or the tags.

Please let me know whether I can help you further.

BR,
Eugen

**Comment by ekaparulin** [comment]
Hi @KN4CK3R ,

I pushed the commits with git CLI utility however, and it may reasoning it?

I use MacOS Ventura, git version 2.30.0. 

Local git config is:

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
	ignorecase = true
	precomposeunicode = true
[user]
	name = E. Kaparulin
	email = e.kaparulin@gmail.com
[remote "origin"]
	url = https://try.gitea.io/eugen.kaparulin/release-bug-test.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "main"]
	remote = origin
	merge = refs/heads/main
```

**Comment by KN4CK3R** [comment]
If you select the branch name here again it works in you repo:
![grafik](https://user-images.githubusercontent.com/1666336/200309034-08c06c1b-234c-4e33-8a94-149ffbcbb630.png)

Still don't know why that is not a problem in my clone.

**Comment by ekaparulin** [comment]
Hi @KN4CK3R ,

 I have created a branch "branch1", added a file, added a tag and pushed everything.

I can see the branch, the new tag and creating the release worked too. But not on the main branch...

**Comment by KN4CK3R** [comment]
The "problem" with your tags is that this code replaces the `tag_target` `main` with the commit id the tag uses
https://github.com/go-gitea/gitea/blob/a0367c2bf05eb89a513972d3895249938b772c44/routers/web/repo/release.go#L282-L300
This change is not visible on the UI, it still shows "Target : main".
Then later it tries to create a release for the branch "commit id" which does not exist.

**Comment by ekaparulin** [comment]
Ok, I got it from the UI point of view,  but if I do it through the API, I get the same error:

```
curl -X 'POST' \
  'https://GITEA_HOST/api/v1/repos/ORG/REPO/releases' \
  -H 'accept: application/json' \
  -H 'authorization: Basic TOKEN' \
  -H 'Content-Type: application/json' \
  -d '{
  "body": "BODY",
  "draft": false,
  "name": "RELEASE_NAME",
  "prerelease": false,
  "tag_name": "EXISTING_TAG",
  "target_commitish": "SHA"
}'
{"message":"Release is has no Tag","url":"https://GITEA/api/swagger"}

```


I am not clear whether it is a user error or application error.

**Comment by wxiaoguang** [comment]
The logic is not ideal here.

I guess the problem is: if you want to create release from a draft, then it needs to be set (updated) to an existing tag first.

**Comment by don4ecap** [comment]
> Works for me ![grafik](https://user-images.githubusercontent.com/1666336/200138243-f64f0cce-aaa0-497e-9d43-cc9c02cf9aee.png)
> 
> Tag 5.0.3 exists already.

Confirmed working on  1.16.8. Thanks!

**Comment by itsdonnix** [comment]
> Works for me ![grafik](https://user-images.githubusercontent.com/1666336/200138243-f64f0cce-aaa0-497e-9d43-cc9c02cf9aee.png)
> 
> Tag 5.0.3 exists already.

Confirmed work on `1.16.8`. Thanks!

**Comment by lunny** [comment]
I think this can be closed. And please feel free to reopen it if the problems still exist.
