### ISSUE TITLE
Gitea 1.1.3 crashes with SIGBUS

### ISSUE THREAD

**Issue by klingtnet** [go-gitea/gitea#2311]
Gitea 1.1.3 build from [dl.gitea.io](https://dl.gitea.io/gitea/1.1.3/gitea-1.1.3-linux-amd64) crashes with `SIGBUS`. The previous version `1.1.2` is running fine in the same environment.
The ansible deployment for my vagrant based test setup can be found [here](https://github.com/klingtnet/spielplatz/blob/master/ansible/playbook.yml#L169-L264).
If you need more details, please let me know.

Contents of `custom/app.ini`:

```ini
APP_NAME = Gitea
RUN_USER = gitea
RUN_MODE = prod

[database]
DB_TYPE  = postgres
HOST     = 127.0.0.1:5432
NAME     = gitea
USER     = gitea
PASSWD   = ThisIsInsecure
SSL_MODE = disable

[repository]
ROOT = /home/gitea/gitea/repos

[server]
SSH_DOMAIN       = localhost
HTTP_PORT        = 10000
ROOT_URL         = http://localhost:10000/
DISABLE_SSH      = false
SSH_PORT         = 22
LFS_START_SERVER = false
OFFLINE_MODE     = false

[mailer]
ENABLED = false

[service]
REGISTER_EMAIL_CONFIRM     = false
ENABLE_NOTIFY_MAIL         = false
DISABLE_REGISTRATION       = true
ENABLE_CAPTCHA             = false
REQUIRE_SIGNIN_VIEW        = false
DEFAULT_KEEP_EMAIL_PRIVATE = false
NO_REPLY_ADDRESS           = noreply.example.org

[picture]
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = false

[session]
PROVIDER = file

[log]
MODE      = console
LEVEL     = Info
ROOT_PATH = /home/gitea/gitea/logs

[security]
INSTALL_LOCK = true
# TODO change this
SECRET_KEY   = xyz
```

Log (`journalctl -u gitea`):

```
. . .
2017/08/15 22:24:38 [I][sql]SELECT indexname, indexdef FROM pg_indexes WHERE schemaname=$1 AND tablename=$2[public protected_branch]
2017/08/15 22:24:38 [W] Table user Column max_repo_creation db default is '-1'::integer, struct default is -1
2017/08/15 22:24:38 [W] Table user Column diff_view_style db default is '''::character varying', struct default is ''
2017/08/15 22:24:38 [I] [sql] SELECT "id", "type", "name", "is_actived", "cfg", "created_unix", "updated_unix" FROM "login_source" WHERE "type"=$1 AND "is_actived"=$2 [args] [6 true]
2017/08/15 22:24:38 [I] Git Version: 2.7.4
unexpected fault address 0x7fca5036c00a
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x7fca5036c00a pc=0x9f76f6]

goroutine 1 [running]:
runtime.throw(0x1315985, 0x5)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc42019cc88 sp=0xc42019cc68
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:287 +0xf4 fp=0xc42019ccd8 sp=0xc42019cc88
code.gitea.io/gitea/vendor/github.com/boltdb/bolt.(*freelist).read(0xc420532720, 0x7fca5036c000)
	/srv/app/src/code.gitea.io/gitea/vendor/github.com/boltdb/bolt/freelist.go:162 +0x26 fp=0xc42019cd48 sp=0xc42019ccd8
code.gitea.io/gitea/vendor/github.com/boltdb/bolt.Open(0xc42053ca60, 0x1b, 0x180, 0xc42019ce60, 0x237c2c0, 0x12c9920, 0xc420052001)
	/srv/app/src/code.gitea.io/gitea/vendor/github.com/boltdb/bolt/db.go:217 +0x3dc fp=0xc42019ce08 sp=0xc42019cd48
code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/store/boltdb.New(0x1c607c0, 0x237aca0, 0xc420532660, 0x6, 0xc420061f70, 0x9d8d22, 0x12d2120)
	/srv/app/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/store/boltdb/store.go:77 +0x270 fp=0xc42019cf10 sp=0xc42019ce08
code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/upsidedown.(*UpsideDownCouch).Open(0xc4204ff880, 0x0, 0x0)
	/srv/app/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/upsidedown/upsidedown.go:308 +0x10c fp=0xc42019cf98 sp=0xc42019cf10
code.gitea.io/gitea/vendor/github.com/blevesearch/bleve.openIndexUsing(0x13369b3, 0x15, 0x0, 0xc42018e850, 0x0, 0x0)
	/srv/app/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index_impl.go:168 +0x61a fp=0xc42019d148 sp=0xc42019cf98
code.gitea.io/gitea/vendor/github.com/blevesearch/bleve.Open(0x13369b3, 0x15, 0x1c66c20, 0xc4205421a0, 0x0, 0x0)
	/srv/app/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index.go:234 +0x3e fp=0xc42019d188 sp=0xc42019d148
code.gitea.io/gitea/models.InitIssueIndexer()
	/srv/app/src/code.gitea.io/gitea/models/issue_indexer.go:86 +0x26c fp=0xc42019d218 sp=0xc42019d188
code.gitea.io/gitea/modules/indexer.NewContext()
	/srv/app/src/code.gitea.io/gitea/modules/indexer/indexer.go:13 +0x20 fp=0xc42019d228 sp=0xc42019d218
code.gitea.io/gitea/routers.GlobalInit()
	/srv/app/src/code.gitea.io/gitea/routers/init.go:64 +0x3a1 fp=0xc42019d2d8 sp=0xc42019d228
code.gitea.io/gitea/cmd.runWeb(0xc4203e9040, 0x0, 0xc4203e9000)
	/srv/app/src/code.gitea.io/gitea/cmd/web.go:170 +0x9d fp=0xc42019d900 sp=0xc42019d2d8
code.gitea.io/gitea/vendor/github.com/urfave/cli.HandleAction(0x11c6580, 0x136dc50, 0xc4203e9040, 0xc4203d8700, 0x0)
	/srv/app/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:471 +0xb9 fp=0xc42019d928 sp=0xc42019d900
code.gitea.io/gitea/vendor/github.com/urfave/cli.Command.Run(0x13135ef, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1337a4c, 0x16, 0x0, ...)
	/srv/app/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/command.go:191 +0xb4b fp=0xc42019dd08 sp=0xc42019d928
code.gitea.io/gitea/vendor/github.com/urfave/cli.(*App).Run(0xc42012d040, 0xc420010120, 0x6, 0x6, 0x0, 0x0)
	/srv/app/src/code.gitea.io/gitea/vendor/github.com/urfave/cli/app.go:241 +0x65f fp=0xc42019dee8 sp=0xc42019dd08
main.main()
	/srv/app/src/code.gitea.io/gitea/main.go:44 +0x3cd fp=0xc42019df88 sp=0xc42019dee8
runtime.main()
	/usr/local/go/src/runtime/proc.go:185 +0x20a fp=0xc42019dfe0 sp=0xc42019df88
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42019dfe8 sp=0xc42019dfe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 19 [syscall]:
os/signal.signal_recv(0xc420025fb0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 18 [chan receive]:
code.gitea.io/gitea/modules/notification.(*notificationService).Run(0x2353238)
	/srv/app/src/code.gitea.io/gitea/modules/notification/notification.go:37 +0x63
created by code.gitea.io/gitea/modules/notification.init.1
	/srv/app/src/code.gitea.io/gitea/modules/notification/notification.go:31 +0x41

goroutine 9 [select]:
code.gitea.io/gitea/modules/log.(*Logger).StartLogger(0xc420152080)
	/srv/app/src/code.gitea.io/gitea/modules/log/log.go:265 +0x2a7
created by code.gitea.io/gitea/modules/log.newLogger
	/srv/app/src/code.gitea.io/gitea/modules/log/log.go:191 +0x11f

goroutine 10 [select]:
code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index.AnalysisWorker(0xc4200116e0, 0xc420011740)
	/srv/app/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/analysis.go:75 +0x13a
created by code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index.NewAnalysisQueue
	/srv/app/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/analysis.go:67 +0xdf

goroutine 11 [select]:
code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index.AnalysisWorker(0xc4200116e0, 0xc420011740)
	/srv/app/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/analysis.go:75 +0x13a
created by code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index.NewAnalysisQueue
	/srv/app/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/analysis.go:67 +0xdf

goroutine 12 [select]:
code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index.AnalysisWorker(0xc4200116e0, 0xc420011740)
	/srv/app/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/analysis.go:75 +0x13a
created by code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index.NewAnalysisQueue
	/srv/app/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/analysis.go:67 +0xdf

goroutine 13 [select]:
code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index.AnalysisWorker(0xc4200116e0, 0xc420011740)
	/srv/app/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/analysis.go:75 +0x13a
created by code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index.NewAnalysisQueue
	/srv/app/src/code.gitea.io/gitea/vendor/github.com/blevesearch/bleve/index/analysis.go:67 +0xdf

goroutine 16 [select]:
code.gitea.io/gitea/modules/log.(*Logger).StartLogger(0xc420052300)
	/srv/app/src/code.gitea.io/gitea/modules/log/log.go:265 +0x2a7
created by code.gitea.io/gitea/modules/log.newLogger
	/srv/app/src/code.gitea.io/gitea/modules/log/log.go:191 +0x11f

goroutine 34 [select]:
code.gitea.io/gitea/modules/log.(*Logger).StartLogger(0xc4200523c0)
	/srv/app/src/code.gitea.io/gitea/modules/log/log.go:265 +0x2a7
created by code.gitea.io/gitea/modules/log.newLogger
	/srv/app/src/code.gitea.io/gitea/modules/log/log.go:191 +0x11f

goroutine 35 [chan receive]:
database/sql.(*DB).connectionOpener(0xc420190640)
	/usr/local/go/src/database/sql/sql.go:837 +0x4a
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:582 +0x212

goroutine 105 [runnable]:
code.gitea.io/gitea/models.CheckRepoStats()
	/srv/app/src/code.gitea.io/gitea/models/repo.go:2000
created by code.gitea.io/gitea/modules/cron.NewContext
	/srv/app/src/code.gitea.io/gitea/modules/cron/cron.go:55 +0x2eb

goroutine 107 [runnable]:
code.gitea.io/gitea/vendor/github.com/gogits/cron.(*Cron).run(0xc4203da640)
	/srv/app/src/code.gitea.io/gitea/vendor/github.com/gogits/cron/cron.go:157
created by code.gitea.io/gitea/vendor/github.com/gogits/cron.(*Cron).Start
	/srv/app/src/code.gitea.io/gitea/vendor/github.com/gogits/cron/cron.go:140 +0x55

goroutine 106 [runnable]:
code.gitea.io/gitea/models.DeleteOldRepositoryArchives()
	/srv/app/src/code.gitea.io/gitea/models/repo.go:1784
created by code.gitea.io/gitea/modules/cron.NewContext
	/srv/app/src/code.gitea.io/gitea/modules/cron/cron.go:66 +0x1ac
```

**Comment by adelowo** [comment]
@lunny any update on this ? I had this same issue on `1.2.0` and `1.1.2` ?

**Comment by daviian** [comment]
@adelowo Have you tried deleting `indexer` folder and restart gitea?

What OS do you use?

**Comment by daviian** [comment]
@adelowo Ok I think this is an already fixed issue in boltdb
@lunny Updating to latest boltdb should fix this. https://github.com/boltdb/bolt/pull/584

**Comment by adelowo** [comment]
Still the same issue, sorry I deleted the comment.. Mine seems to be more related to postgresql and SSL connection. I only get something of this sort whenever ssl is set to any other thing apart from "disable"... With "disable", the connection doesn't even go through and it gives "provide ssl options"

**Comment by daviian** [comment]
@adelowo The panic comes from boltdb, there's no postgresql involved here.

**Comment by klingtnet** [comment]
I will close this issue because I am building gitea from source and I use version 1.2.0 now which works just fine.

**Comment by daviian** [comment]
@klingtnet Just out of curiosity. What OS did you use to build gitea at the time you opened this issue?
For example Windows 10 WSL (Ubuntu on Windows) has a known bug regarding boltdb ;-)

**Comment by klingtnet** [comment]
@daviian It was an Arch Linux. The time I opened the issue I used the official builds.

**Comment by bkcsoft** [comment]
Was this an issue in 1.1.4? If so we need a fix for that :(

**Comment by daviian** [comment]
@bkcsoft ~I think an update of boltdb should be sufficient to resolve this.~ Saw that boltdb is fixed by blevesearch :/

**Comment by lunny** [comment]
Just update boltdb will fix this?

**Comment by daviian** [comment]
I found this issue showing same log entries https://github.com/boltdb/bolt/issues/513

**Comment by lunny** [comment]
But it's strange Gitea's bolt db vendor should have a version after 2016.07 since Gitea 1.0 was released 2016.12

**Comment by strk** [comment]
Is this still a problem with latest (1.3.2) release ?

**Comment by strk** [comment]
I'd close this out for lack of feedback

**Comment by lafriks** [comment]
Closing, reopen if there is still issue in latest version
