### ISSUE TITLE
Organization-wide projects bugs

### ISSUE THREAD

**Issue by delvh** [go-gitea/gitea#23318]
### Description

At the moment, organization-wide projects **are riddled with bugs**, based on preliminary user feedback from 1.19.0-rc1:
They are
- [x] no one (not even the site admin) can edit/delete org projects, see screenshots 1 and 3
- [x] repo projects allow to set the `card preview type` during creation. Organization projects don't, see screenshots 5 and 6
- [x] Org projects ignore the column color, see screenshots 1 and 2, the right column should have the color `#ff0000`.

These issues can be fixed by sharing the code of repo projects with the organization projects.

Furthermore, the following issues are present:
- [x] The organization `Projects` tab misses quite a few tabs as well as the organization settings, see screenshots 1, 3, and 5.
- [ ] When creating an org project, and adding a second column
  - [x] and setting the second one as default, the initially created column disappears permanently, until the second column is deleted again. Happens both for repo- and org-projects. (#23401)
  - [ ] only the second column can be edited, the first one can't, see screenshot 1 and 2. Happens both for repo- and org-projects (#29873)
- [x] If a repo disables projects, its issues cannot be assigned to org-wide projects either. While the current logic for that is clear (`if isPackagesEnabled <list available projects> end`), this would probably still be useful to implement.
- [x] Both organization and repo projects cannot edit the column color anymore
- [x] If you click on the PR that closed an issue inside an org-wide project, you get redirected to `$URL/pull/$ID` instead of `$URL/$USER/$REPO/pull/$ID`

### Screenshot 1: Org project appearance
![image](https://user-images.githubusercontent.com/51889757/222985160-e153c1b8-eeff-4f77-ab77-a496543e810b.png)
### Screenshot 2: Repo project appearance 
![image](https://user-images.githubusercontent.com/51889757/222985205-d1505e08-a1cf-40d0-9fcd-c9b0186a8d3c.png)
### Screenshot 3: org repo projects list
![image](https://user-images.githubusercontent.com/51889757/222985245-915a25e8-5477-425c-85d1-7b8464594fb3.png)
### Screenshot 4: Repo projects list
![image](https://user-images.githubusercontent.com/51889757/222985263-a778064c-8719-4493-a7ea-5ba2227c8b96.png)
### Screenshot 5: New org project
![image](https://user-images.githubusercontent.com/51889757/222985331-15350804-51ee-4b25-b258-d26281cf9e04.png)
### Screenshot 6: New repo project
![image](https://user-images.githubusercontent.com/51889757/222985371-bcf3fc55-c9c5-4dcc-9b16-f41e57048c5d.png)

### Gitea Version

1.20.0+dev-90-gea7f0d6fc

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Linux

### Browser Version

Firefox 110.0

**Comment by yp05327** [comment]
Thanks for your summarization.

I tried to fix some of them about one month ago
The first PR is https://github.com/go-gitea/gitea/pull/22705, but it seems not easy to fix it, as I found more problems in CI result:
https://github.com/go-gitea/gitea/pull/23109
https://github.com/go-gitea/gitea/issues/23349

The second one is https://github.com/go-gitea/gitea/pull/22865, but it is too big, I'm spliting this PR into several small ones. then it will be easier to review:
https://github.com/go-gitea/gitea/pull/23325
https://github.com/go-gitea/gitea/pull/23326
https://github.com/go-gitea/gitea/pull/23327

**Comment by yp05327** [comment]
@delvh 
> Org projects ignore the column color, see screenshots 1 and 2, the right column should have the color #ff0000.

I notice that we can not edit the column color in both repo and org/user projects in current main branch.
In 1.18.5, I can edit the column color in both repo projects.
It seems that the link is incorrect. I will fix this later.
Can you confirm this problem, and if it is possible, add to the task list?
Thanks.

**Comment by yp05327** [comment]
>  repo projects allow to set the card preview type during creation. Organization projects don't, see screenshots 5 and 6

The select box will display nothing even if one is selected.

**Comment by 6543** [comment]
org projects can only be assigned in issues where it's repo as projects enabled too

**Comment by delvh** [comment]
>  If a repo disables projects, its issues cannot be assigned to org-wide projects either. While the current logic for that is clear (if isPackagesEnabled <list available projects> end), this would probably still be useful to implement.

?

**Comment by HesterG** [comment]
Find another issue, Buttons used on "set defualt" and "delete column" are not proper, so cancel will disappear on hover. And this occurs on both repo/org projects:

https://user-images.githubusercontent.com/17645053/231639604-5e3ea04d-3ce4-478d-b0e7-189ac0dc19c2.mov

IMO It is a good idea to use `delete_modal_actions.tmpl` here both to fix this issue and keep ui consistency as suggested by [TODO here](https://github.com/go-gitea/gitea/blob/4299c3b7db61f8741eca0ba3d663bb65745a4acc/templates/projects/view.tmpl#L161)
I will open a PR to solve this later.

**Comment by yp05327** [comment]
Maybe this problem is caused by css?
The button will not disappear in dark mode.

**Comment by HesterG** [comment]
> Maybe this problem is caused by css? The button will not disappear in dark mode.
> 
> If I open devtools in chrome, the button works well in dark mode. But if I close DevTools, the button will have no changes when mouse move across the button.
> 
> Open devtools: mouse not on the button: ![image](https://user-images.githubusercontent.com/18380374/231646323-f910c053-fad2-4e68-a131-6daa7a96b36f.png) mouse on the button: ![image](https://user-images.githubusercontent.com/18380374/231646367-98e5bfb6-d3a0-4195-be9b-6819c46eea37.png)
> 
> Close devtools (always same as `mouse on the button`): ![image](https://user-images.githubusercontent.com/18380374/231646614-a9d19c31-25d7-415f-86bb-e8f83c9f54d9.png) Tested in gitea.com

Yes it is caused by css, the reason why `arc-green` theme looks good is because the color for the text on cancel button on hovering is different from `gitea` theme. And here it might be more suitable to use `delete_modal_actions.tmpl` also for consistency, like some other places with the similar modal ui:

e.g. Delete Project UI:

<img width="853" alt="截屏2023-04-13 13 58 36" src="https://user-images.githubusercontent.com/17645053/231667034-b103758d-68e2-4731-8742-9e54fe9576eb.png">

**Comment by silverwind** [comment]
Looks like some bug in the button colors. I'd argue the modal buttons should be full red/green, with no inner grey border, on both themes.

**Comment by silverwind** [comment]
> Do you mean like this?

I envisioned with border, but your style looks even better, let's do it.

**Comment by HesterG** [comment]
> > Do you mean like this?
> 
> I envisioned with border, but your style looks even better, let's do it.

add a commit https://github.com/go-gitea/gitea/pull/24097/commits/1df04eef57e9b9d8020cd460dea87cdd0338b2dd to do this style

**Comment by delvh** [comment]
Closed accidentally.

**Comment by delvh** [comment]
Found another one: If you click on the PR that closed an issue inside an org-wide project, you get redirected to `$URL/pull/$ID` instead of `$URL/$USER/$REPO/pull/$ID`

**Comment by brenthuisman** [comment]
> Found another one: If you click on the PR that closed an issue inside an org-wide project, you get redirected to `$URL/pull/$ID` instead of `$URL/$USER/$REPO/pull/$ID`

Just got bit by this one (during a demo of Gitea). Tracking issues on a org board or third repo board are broken.

**Comment by denyskon** [comment]
Confirmed that the last remaining issues were resolved by #28805 and #28806

**Comment by delvh** [comment]
I think
> When creating an org project, and adding a second column only the second column can be edited, the first one can't.
See screenshot 1 and 2. Happens both for repo- and org-projects

is still present.
But apart from that, yes, agreed, we slowly seem to have gotten rid of the project bugs. Finally :relieved:

**Comment by denyskon** [comment]
@delvh Why should the default column be edited? If you don't like it, create a new one and set it as default. I think it is expected behaviour.

**Comment by delvh** [comment]
![grafik](https://github.com/go-gitea/gitea/assets/51889757/d151095f-8143-4cc9-a112-12e6bacc3b81)

Why do we need such a workaround for these things?

**Comment by denyskon** [comment]
Well maybe it's because I always considered it to be a feature, not a bug, I don't understand where the problem is, but for me the default column always was something that is there for empty projects still to be able to contain issues, and if you need more you create a new column. We can change it of course.

**Comment by delvh** [comment]
That's not what I mean.
What I mean is:
Why can't I rename or recolor the default board but everything else?
However, if I change the default board, I suddenly can?

**Comment by denyskon** [comment]
Because thats how it is!!!!!!!!!11!1!1!1

Maybe modern-day technology just educates us to accept issues as if they were intended?

Anyways, I'll check if it can be adapted easily....

**Comment by denyskon** [comment]
@delvh Currently, this non-adaptable board is generated dynamically when getting a project fromDB which doesn't contain a board. It could theoretically be fixed by simply creating a default board when creating an empty project.

**Comment by delvh** [comment]
Instead of misusing this issue for it, let's move the discussion to another one.
