### ISSUE TITLE
Can login with docker login but can't do a docker push

### ISSUE THREAD

**Issue by carolosf** [go-gitea/gitea#25374]
### Description

I can't reproduce on try.gitea.io but using the hostname for the example

I am using ldap for authentication with a kubernetes ingress accepting a particular hostname. 

When I do `docker login hostname` it logs in fine even if I enter the wrong password
```
docker login try.gitea.io
```

I get an authorisation required message when I try push.

```
docker tag ubuntu try.gitea.io/carolosf/ubuntu:latest
docker push try.gitea.io/carolosf/ubuntu:latest
The push refers to repository [git.example.com/demo/ubuntu]
ab318285541e: Preparing
unauthorized: authentication required
```

I can upload other packages ok

```
curl -X PUT -u carolosf:password -T file.yaml https://git.example.com/api/packages/carolosf/generic/depploytest/v1/file.yaml
```
 

### Gitea Version

1.19.3

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

k3s kubernetes latest docker image

### Database

SQLite

**Comment by KN4CK3R** [comment]
Can't try at the moment but that should be fixed... See #20563 and #22119.

**Comment by KN4CK3R** [comment]
Tried it and can't reproduce the login error with the current main branch.

**Comment by carolosf** [comment]
Strange - just tried with gitea/gitea:nightly-rootless arm64 image f68db5dd1094
and still getting the login issue... Any idea why?

**Comment by carolosf** [comment]
Could it be because I'm authenticating with LDAP?

**Comment by KN4CK3R** [comment]
There should be no difference. Could you test it with a local account / another test instance without LDAP?

**Comment by carolosf** [comment]
So I deployed a new kubernetes deployment of gitea with the latest nightly and it worked.
I then connected LDAP to it and that also worked as expected.

Eventually I found that my original instance had ROOT_URL= set to http://git.example.com instead of https://git.example.com I changed the config and restarted it and it started working.

By working I mean it started rejecting incorrect logins as expected and also a docker push worked.
