### ISSUE TITLE
Ability to edit and delete Time Tracking entries

### ISSUE THREAD

**Issue by Caballerog** [go-gitea/gitea#2642]
## Description

I'm testing the feature Time tracking (https://github.com/go-gitea/gitea/issues/967), which I think that is very useful, but should allow that the user modify or delete a time tracking event because It can make a mistake. 

Imagine that I made the mistake of not remembering to close a task or that I entered a very large number in error. It would make this feature useless.

At the moment, I am able to update using the database directly.

What do you think about?

**Comment by kolaente** [comment]
Should be an option for admins only, maybe with you can only delete your own times if you're not an admin.

**Comment by Morlinest** [comment]
Maybe more detailed settings for who can delete it, like:
1. Admin
2. Repo owner
3. Repo maintainers
4. User (who created time record)
5. Specific user

Another thing is to lock any modification (eg. monthly report) for repository, user or combination of both, but that can be new feature...

**Comment by lafriks** [comment]
I think only repo admin & user who created time record can edit&delete it

**Comment by Caballerog** [comment]
I think that should be very simple like @lafriks said. I.e, only repo admin & user who created time record should can edit&delete it.

**Comment by jonasfranz** [comment]
I think that we have two options for this.

1. A separate modal with the time tracking entries with options to delete/edit them.
2. Buttons at the comment entry of every time tracking comment. This need some changes in the database which would require it to add this to the `1.3.0` milestone because comments before the change could not be used for editing / deleting because of the lack of relationship to the time tracking database entry.

**Comment by jonasfranz** [comment]
@MrHaroldA I'm currently working on this.

**Comment by jlcummings** [comment]
Instead of deleting or directly editing an entry, which could smash traceability/accountability, I would rather see an 'Adjustment' action that allows adding negative (or positive) entries to the cumulative time duration.  There should be two base forms of adjustment, with three options:

1.  Soft, One-For-One (Referential Adjustment): when a particular prior time entry is referenced explicitly, negative (or positive) time can be added.  This could be available to the person who made the original erroneous entry, or a project maintainer.  This should be the typical, day-to-day use case.
1.  Soft, One-For-Many (Referential Adjustment): when a particular set of prior time entries are referenced explicitly for the negative (or positive) time entry, indicating those were erroneous and this adjustment attempts to correct them together in one cumulative adjustment.  This could be available to the person who made the originally erroneous referenced entries, or the project maintainer.  This would be an uncommon, but helpful use-case for bulk-maintenance.
1. Hard (Non-Referential Adjustment): where only the project owner could add negative time without referencing prior time keeping entries.  This is where the project owner/primary maintainer knows of an overall error in timekeeping, and wants to address it with a hammer.  This should typically be a rare, but essential use-case.

This promotes an accounting style of time management, where you can't change what is done, but you can acknowledge a mistake, correct it the best you can, and move forward.

**Comment by MrHaroldA** [comment]
> This promotes an accounting style of time management, where you can't change what is done, but you can acknowledge a mistake, correct it the best you can, and move forward.

This is way overkill for our needs: some simple logging of who changed the logged hours would suffice in all our use cases.

**Comment by Diverti** [comment]
I hope it will be implemented, would be awesome. Also a table to overview all the tracked time in the repo would be great also.

**Comment by guillep2k** [comment]
@FriedrichVonSchnitzel I don't use the time tracking function, but I've just read a comment in another thread from a user saying that their problems with time tracking not working were solved when they've upgraded to 1.11.4. Can you check if that's your case too? Also, I wouldn't stay on 1.11.0 because it has some annoying bugs that have been fixed in 1.11.3 and up.

**Comment by FriedrichVonSchnitzel** [comment]
@guillep2k thank you for your reply, we have updated to 1.11.4, but the red cross next to the entry is still not displayed. I've also tried unchecking the "Let Only Contributors Track Time" in the repository settings.

**Comment by chriseaton** [comment]
This has got me a few times, I accidentally entered the wrong time and there's no way to adjust it. I think, at a minimum, be able to clear it, or just edit it. It already shows it in the activity of the issue anyways? Why make this more difficult than it needs to be.

If no edit or delete, how about being able to subtract time?

**Comment by noerw** [comment]
I'll try to implement this in the coming days/weeks.

As a stop gap: the [`tea` CLI](https://gitea.com/gitea/tea) for gitea can already reset and delete specific times via the API.
