### ISSUE TITLE
[BUG][API] Issue/pr attachments return wrong download url

### ISSUE THREAD

**Issue by mmarif4u** [go-gitea/gitea#27204]
### Description

The issue attachment API return the following:

```
[
	{
		"id": 58540,
		"name": "Screenshot_20230919_133134.png",
		"size": 41611,
		"download_count": 16,
		"created_at": "2023-09-19T08:37:33Z",
		"uuid": "c9bf83dc-8d08-460e-9986-ee7f292bccd7",
		"browser_download_url": "https://codeberg.org/api/repos/gitnex/GitNex/releases/0/assets/58540"
	},
	{
		"id": 58541,
		"name": "Screenshot_20230919_133201.png",
		"size": 41475,
		"download_count": 17,
		"created_at": "2023-09-19T08:37:33Z",
		"uuid": "e5f07ce2-4179-43ae-81a2-09e4d319aab2",
		"browser_download_url": "https://codeberg.org/api/repos/gitnex/GitNex/releases/0/assets/58541"
	},
	{
		"id": 58542,
		"name": "Screenshot_20230919_133224.png",
		"size": 19559,
		"download_count": 16,
		"created_at": "2023-09-19T08:37:34Z",
		"uuid": "6bed5cd4-2f82-4566-bea7-605d12af498d",
		"browser_download_url": "https://codeberg.org/api/repos/gitnex/GitNex/releases/0/assets/58542"
	}
]
```

This is a possible bug because the `browser_download_url` is broken to me. This may also affect the comments attachment API too.
The `browser_download_url` should be a proper downloadable URL like how it is in the releases.

### Gitea Version

1.20.3

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

Codeberg and Gitea 1.20.3 for testing on local setup.

https://codeberg.org/api/v1/repos/gitnex/GitNex/issues/1300/assets

### Database

None

**Comment by KN4CK3R** [comment]
I think this was fixed in 1.21 already,

**Comment by mmarif4u** [comment]
I just quickly checked 1.21 rc0 and the issue is still there.

**Comment by lunny** [comment]
Maybe it could be fixed by #26430 .

**Comment by mmarif4u** [comment]
Release `1.20.5` apparently did not fix this issue as the PR mentioned by @lunny is back-ported.

**Comment by lunny** [comment]
The backport is #27378. That PR allow token visit web routers `/{username}/{reponame}/releases/download/{vTag}/{fileName}`, but looks like the API's `browser_download_url` wasn't changed to that router.

**Comment by lunny** [comment]
@mmarif4u Can you help to confirm #27486 fix the problem?

**Comment by mmarif4u** [comment]
@lunny sure. Can you point me to download a binary for linux_x64 if possible as I do not have Gitea dev setup.

**Comment by lunny** [comment]
> @lunny sure. Can you point me to download a binary for linux_x64 if possible as I do not have Gitea dev setup.

Unfortunately there is not and if you don't need sqlite support I can build one for you.

**Comment by mmarif4u** [comment]
Feel free to share, I can set it up with any other db like MySQL or MariaDB even though I use sqlite for testing.

**Comment by lunny** [comment]
> Feel free to share, I can set it up with any other db like MySQL or MariaDB even though I use sqlite for testing.

What's your favorite OS?

**Comment by mmarif4u** [comment]
I work on Manjaro mostly.

**Comment by lunny** [comment]
https://gitea.com/lunny/packages/raw/branch/main/gitea-27486.zip

**Comment by mmarif4u** [comment]
Thanks. I have tested it and the URL seems to be the same as web version now.

`domain.com/attachments/81030792-78fd-4277-bf6f-6930bc80d618` which works for public files. For private repository files, I have tested with passing token as query param and it worked also.

Haven't tested with token as header for private repositories. But maybe that is out of scope or not a needed thing right now.

All good now.

**Comment by lunny** [comment]
> Thanks. I have tested it and the URL seems to be the same as web version now.
> 
> `domain.com/attachments/81030792-78fd-4277-bf6f-6930bc80d618` which works for public files. For private repository files, I have tested with passing token as query param and it worked also.
> 
> Haven't tested with token as header for private repositories. But maybe that is out of scope or not a needed thing right now.
> 
> All good now.

Yes, since web routers cannot be ignored and Github also point to a web router. I revert my previous change. Thank you for your confirmation.
