### ISSUE TITLE
upgrade to 1.21.0 view repo on web gives 500 error: GetRecentlyPushedBranches, mssql: Cannot resolve the collation conflict between "Latin1_General_CS_AS" and "Latin1_General_CI_AS" in the equal to operation.

### ISSUE THREAD

**Issue by shanepowell** [go-gitea/gitea#28079]
### Description

After upgrading to 1.21.0 and starting the service.  Trying to view any repo on the web site displays the following error:

500

GetRecentlyPushedBranches, mssql: Cannot resolve the collation conflict between "Latin1_General_CS_AS" and "Latin1_General_CI_AS" in the equal to operation.

In the log I see:
2023/11/16 07:20:39 ...eb/routing/logger.go:102:func1() [I] router: completed POST /IPFX/OnTrackWeb.git/git-upload-pack for 10.4.0.15:60717, 200 OK in 2586.4ms @ repo/githttp.go:492(repo.ServiceUploadPack)
2023/11/16 07:20:41 ...ers/web/repo/view.go:1000:renderCode() [E] GetRecentlyPushedBranches: mssql: Cannot resolve the collation conflict between "Latin1_General_CS_AS" and "Latin1_General_CI_AS" in the equal to operation.

### Gitea Version

1.21.0

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Setup:
* Local Windows Server
* MSSQL Server running on the same machine

GITEA is installed via chocolatey.  So the upgrade was just 'choco upgrade gitea' stop/starting the service around the command.

### Database

MSSQL

**Comment by KazzmanK** [comment]
As per
```
	subQuery := builder.Select("head_branch").From("pull_request").
		InnerJoin("issue", "issue.id = pull_request.issue_id").
		Where(builder.Eq{
			"pull_request.head_repo_id": repoID,
			"issue.is_closed":           false,
		})
	err := db.GetEngine(ctx).
		Where("pusher_id=? AND is_deleted=?", userID, false).
		And("name <> ?", excludeBranchName).
		And("repo_id = ?", repoID).
		And("commit_time >= ?", time.Now().Add(-time.Hour*6).Unix()).
		NotIn("name", subQuery).
		OrderBy("branch.commit_time DESC").
		Limit(2).
		Find(&branches)
```
somewhere in this query column collation is different from server collation, or other table collation, resulting in error.
To be absolutely sure, please share your server collation and column collations for tables `pull_request` and `issue`

**Comment by SoulSeekkor** [comment]
If it helps I also have an instance of Gitea running on Windows Server and MSSQL.  Currently haven't upgraded yet and still on 1.20.4, but the collation for the database and all text columns in those two tables is SQL_Latin1_General_CP1_CI_AS for us.

**Comment by shanepowell** [comment]
For me, both those tables as: Latin1_General_CI_AS

**Comment by R3DST0RM** [comment]
I do get the same error but with different collation:

```bash
GetRecentlyPushedBranches, Error 1267 (HY000): Illegal mix of collations (utf8mb4_0900_ai_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
```

`pull request` and `issue` have `utf8mb4_general_ci` as column and table collation.

I noticed though, that a few tables have a different collation:
```
+--------------+---------------------------+--------------------+
| TABLE_SCHEMA | TABLE_NAME                | TABLE_COLLATION    |
+--------------+---------------------------+--------------------+
| gitea        | access                    | utf8mb4_general_ci |
| gitea        | access_token              | utf8mb4_general_ci |
| gitea        | action                    | utf8mb4_general_ci |
| gitea        | action_artifact           | utf8mb4_0900_ai_ci |
| gitea        | action_run                | utf8mb4_0900_ai_ci |
| gitea        | action_run_index          | utf8mb4_0900_ai_ci |
| gitea        | action_run_job            | utf8mb4_0900_ai_ci |
| gitea        | action_runner             | utf8mb4_0900_ai_ci |
| gitea        | action_runner_token       | utf8mb4_0900_ai_ci |
| gitea        | action_schedule           | utf8mb4_0900_ai_ci |
| gitea        | action_schedule_spec      | utf8mb4_0900_ai_ci |
| gitea        | action_task               | utf8mb4_0900_ai_ci |
| gitea        | action_task_output        | utf8mb4_0900_ai_ci |
| gitea        | action_task_step          | utf8mb4_0900_ai_ci |
| gitea        | action_tasks_version      | utf8mb4_0900_ai_ci |
| gitea        | action_variable           | utf8mb4_0900_ai_ci |
| gitea        | app_state                 | utf8mb4_general_ci |
| gitea        | attachment                | utf8mb4_general_ci |
| gitea        | badge                     | utf8mb4_general_ci |
| gitea        | branch                    | utf8mb4_0900_ai_ci |
| gitea        | collaboration             | utf8mb4_general_ci |
| gitea        | comment                   | utf8mb4_general_ci |
| gitea        | commit_status             | utf8mb4_general_ci |
| gitea        | commit_status_index       | utf8mb4_general_ci |
| gitea        | dbfs_data                 | utf8mb4_0900_ai_ci |
| gitea        | dbfs_meta                 | utf8mb4_0900_ai_ci |
| gitea        | deploy_key                | utf8mb4_general_ci |
| gitea        | email_address             | utf8mb4_general_ci |
| gitea        | email_hash                | utf8mb4_general_ci |
| gitea        | external_login_user       | utf8mb4_general_ci |
| gitea        | follow                    | utf8mb4_general_ci |
| gitea        | gpg_key                   | utf8mb4_general_ci |
| gitea        | gpg_key_import            | utf8mb4_general_ci |
| gitea        | hook_task                 | utf8mb4_general_ci |
| gitea        | issue                     | utf8mb4_general_ci |
| gitea        | issue_assignees           | utf8mb4_general_ci |
| gitea        | issue_content_history     | utf8mb4_general_ci |
| gitea        | issue_dependency          | utf8mb4_general_ci |
| gitea        | issue_index               | utf8mb4_general_ci |
| gitea        | issue_label               | utf8mb4_general_ci |
| gitea        | issue_user                | utf8mb4_general_ci |
| gitea        | issue_watch               | utf8mb4_general_ci |
| gitea        | label                     | utf8mb4_general_ci |
| gitea        | language_stat             | utf8mb4_general_ci |
| gitea        | lfs_lock                  | utf8mb4_general_ci |
| gitea        | lfs_meta_object           | utf8mb4_general_ci |
| gitea        | login_source              | utf8mb4_general_ci |
| gitea        | milestone                 | utf8mb4_general_ci |
| gitea        | mirror                    | utf8mb4_general_ci |
| gitea        | notice                    | utf8mb4_general_ci |
| gitea        | notification              | utf8mb4_general_ci |
| gitea        | oauth2_application        | utf8mb4_general_ci |
| gitea        | oauth2_authorization_code | utf8mb4_general_ci |
| gitea        | oauth2_grant              | utf8mb4_general_ci |
| gitea        | org_user                  | utf8mb4_general_ci |
| gitea        | package                   | utf8mb4_general_ci |
| gitea        | package_blob              | utf8mb4_general_ci |
| gitea        | package_blob_upload       | utf8mb4_general_ci |
| gitea        | package_cleanup_rule      | utf8mb4_0900_ai_ci |
| gitea        | package_file              | utf8mb4_general_ci |
| gitea        | package_property          | utf8mb4_general_ci |
| gitea        | package_version           | utf8mb4_general_ci |
| gitea        | project                   | utf8mb4_general_ci |
| gitea        | project_board             | utf8mb4_general_ci |
| gitea        | project_issue             | utf8mb4_general_ci |
| gitea        | protected_branch          | utf8mb4_general_ci |
| gitea        | protected_tag             | utf8mb4_general_ci |
| gitea        | public_key                | utf8mb4_general_ci |
| gitea        | pull_auto_merge           | utf8mb4_general_ci |
| gitea        | pull_request              | utf8mb4_general_ci |
| gitea        | push_mirror               | utf8mb4_general_ci |
| gitea        | reaction                  | utf8mb4_general_ci |
| gitea        | release                   | utf8mb4_general_ci |
| gitea        | renamed_branch            | utf8mb4_general_ci |
| gitea        | repo_archiver             | utf8mb4_general_ci |
| gitea        | repo_indexer_status       | utf8mb4_general_ci |
| gitea        | repo_redirect             | utf8mb4_general_ci |
| gitea        | repo_topic                | utf8mb4_general_ci |
| gitea        | repo_transfer             | utf8mb4_general_ci |
| gitea        | repo_unit                 | utf8mb4_general_ci |
| gitea        | repository                | utf8mb4_general_ci |
| gitea        | review                    | utf8mb4_general_ci |
| gitea        | review_state              | utf8mb4_general_ci |
| gitea        | secret                    | utf8mb4_0900_ai_ci |
| gitea        | session                   | utf8mb4_general_ci |
| gitea        | star                      | utf8mb4_general_ci |
| gitea        | stopwatch                 | utf8mb4_general_ci |
| gitea        | system_setting            | utf8mb4_general_ci |
| gitea        | task                      | utf8mb4_general_ci |
| gitea        | team                      | utf8mb4_general_ci |
| gitea        | team_invite               | utf8mb4_general_ci |
| gitea        | team_repo                 | utf8mb4_general_ci |
| gitea        | team_unit                 | utf8mb4_general_ci |
| gitea        | team_user                 | utf8mb4_general_ci |
| gitea        | topic                     | utf8mb4_general_ci |
| gitea        | tracked_time              | utf8mb4_general_ci |
| gitea        | two_factor                | utf8mb4_general_ci |
| gitea        | upload                    | utf8mb4_general_ci |
| gitea        | user                      | utf8mb4_general_ci |
| gitea        | user_badge                | utf8mb4_general_ci |
| gitea        | user_open_id              | utf8mb4_general_ci |
| gitea        | user_redirect             | utf8mb4_general_ci |
| gitea        | user_setting              | utf8mb4_general_ci |
| gitea        | version                   | utf8mb4_general_ci |
| gitea        | watch                     | utf8mb4_general_ci |
| gitea        | webauthn_credential       | utf8mb4_general_ci |
| gitea        | webhook                   | utf8mb4_general_ci |
+--------------+---------------------------+--------------------+
```

**Comment by KazzmanK** [comment]
If you run DOCTOR , what is the new outcome of said collations ?

**Comment by R3DST0RM** [comment]
Using doctor all tables and columns got converted to `utf8mb4_general_ci` (which in my case is for MySQL)

**Comment by KazzmanK** [comment]
for MySql there were changes, especially for utf8mb4

**Comment by SoulSeekkor** [comment]
For me the server collation, databases, and columns are all SQL_Latin1_General_CP1_CI_AS.  This is with SQL Server 2019.  I haven't done anything with gitea doctor yet, I haven't seen that before.

**Comment by lunny** [comment]
> For me the server collation, databases, and columns are all SQL_Latin1_General_CP1_CI_AS. This is with SQL Server 2019. I haven't done anything with gitea doctor yet, I haven't seen that before.

gitea doctor will only fix mysql charactor problem.

**Comment by lunny** [comment]
Please check wether all the columns collation are the same.

```sql
SELECT
    col.name, col.collation_name
FROM 
    sys.columns col
WHERE
    object_id = OBJECT_ID('branch')
```

If all the column's collations are the same, then check another two tables `pull_request` and `issue` like above.

**Comment by shanepowell** [comment]
SELECT name, collation_name  
FROM sys.databases 

Output:
master	Latin1_General_CS_AS
tempdb	Latin1_General_CS_AS
model	Latin1_General_CS_AS
msdb	Latin1_General_CS_AS
gitea	Latin1_General_CI_AS


select convert(sysname, serverproperty(N'collation')) AS [Collation]

Output:
Latin1_General_CS_AS

SELECT
    col.name, col.collation_name
FROM 
    sys.columns col
WHERE
    object_id = OBJECT_ID('branch')

Output:
id	NULL
repo_id	NULL
name	Latin1_General_CI_AS
commit_id	Latin1_General_CI_AS
commit_message	Latin1_General_CI_AS
pusher_id	NULL
is_deleted	NULL
deleted_by_id	NULL
deleted_unix	NULL
commit_time	NULL
created_unix	NULL
updated_unix	NULL



SELECT
    col.name, col.collation_name
FROM 
    sys.columns col
WHERE
    object_id = OBJECT_ID('pull_request')

Output:
id	NULL
type	NULL
status	NULL
conflicted_files	Latin1_General_CS_AS
commits_ahead	NULL
commits_behind	NULL
changed_protected_files	Latin1_General_CS_AS
issue_id	NULL
index	NULL
head_repo_id	NULL
base_repo_id	NULL
head_branch	Latin1_General_CS_AS
base_branch	Latin1_General_CS_AS
merge_base	Latin1_General_CS_AS
allow_maintainer_edit	NULL
has_merged	NULL
merged_commit_id	Latin1_General_CS_AS
merger_id	NULL
merged_unix	NULL
flow	NULL


SELECT
    col.name, col.collation_name
FROM 
    sys.columns col
WHERE
    object_id = OBJECT_ID('issue')

Output:
id	NULL
repo_id	NULL
index	NULL
poster_id	NULL
original_author	Latin1_General_CS_AS
original_author_id	NULL
name	Latin1_General_CS_AS
content	Latin1_General_CS_AS
milestone_id	NULL
priority	NULL
is_closed	NULL
is_pull	NULL
num_comments	NULL
ref	Latin1_General_CS_AS
deadline_unix	NULL
created_unix	NULL
updated_unix	NULL
closed_unix	NULL
is_locked	NULL
pin_order	NULL


I don't know how to run gitea doctor so someone will have to point me to something on how to run that if you think I need to.

**Comment by labronic** [comment]
> I'm running gitea in docker. When I run `docker exec srv-captain--git.1.jeglmys2pdkv7v05q7inewhlc gitea doctor convert`, I get an error: `...s/setting/setting.go:180:loadRunModeFrom() [F] Gitea is not supposed to be run as root. Sorry. If you need to use privileged TCP ports please instead use setcap and the `cap_net_bind_service` permission`.
> 
> When running without root, I get another - `permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock:`.
> 
> I'm sure I'm doing something wrong :) But what?

Attempt to log into the container, typically using the command `docker exec -ti <name of your Gitea container> /bin/bash.` Once inside, execute the command `su git,` followed by `gitea doctor convert.`
Unfortunately, in my case, the result was as follows:
gitea doctor convert
2024/02/26 07:57:55 ...md/doctor_convert.go:32:runDoctorConvert() [I] AppPath: /usr/local/bin/gitea
2024/02/26 07:57:55 ...md/doctor_convert.go:33:runDoctorConvert() [I] AppWorkPath: /data/gitea
2024/02/26 07:57:55 ...md/doctor_convert.go:34:runDoctorConvert() [I] Custom path: /data/gitea
2024/02/26 07:57:55 ...md/doctor_convert.go:35:runDoctorConvert() [I] Log path: /data/gitea/log
2024/02/26 07:57:55 ...md/doctor_convert.go:36:runDoctorConvert() [I] Configuration file: /data/gitea/conf/app.ini
2024/02/26 07:57:55 cmd/main.go:117:func1() [I] [SQL] SELECT 'ALTER TABLE ' + OBJECT_NAME(SC.object_id) + ' MODIFY SC.name NVARCHAR(' + CONVERT(VARCHAR(5),SC.max_length) + ')'
FROM SYS.columns SC
JOIN SYS.types ST
ON SC.system_type_id = ST.system_type_id
AND SC.user_type_id = ST.user_type_id
WHERE ST.name ='varchar' [] - 56.781156ms
2024/02/26 07:57:55 ...md/doctor_convert.go:47:runDoctorConvert() [F] Failed to convert database from varchar to nvarchar: mssql: Incorrect syntax near 'MODIFY'.
2024/02/26 07:57:55 cmd/main.go:117:func1() [I] [SQL] ALTER TABLE upload MODIFY SC.name NVARCHAR(40) [] - 4.071094ms

Version Gitea: 1.21.6

**Comment by lunny** [comment]
> > I'm running gitea in docker. When I run `docker exec srv-captain--git.1.jeglmys2pdkv7v05q7inewhlc gitea doctor convert`, I get an error: `...s/setting/setting.go:180:loadRunModeFrom() [F] Gitea is not supposed to be run as root. Sorry. If you need to use privileged TCP ports please instead use setcap and the `cap_net_bind_service` permission`.
> > When running without root, I get another - `permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock:`.
> > I'm sure I'm doing something wrong :) But what?
> 
> Attempt to log into the container, typically using the command `docker exec -ti <name of your Gitea container> /bin/bash.` Once inside, execute the command `su git,` followed by `gitea doctor convert.` Unfortunately, in my case, the result was as follows: gitea doctor convert 2024/02/26 07:57:55 ...md/doctor_convert.go:32:runDoctorConvert() [I] AppPath: /usr/local/bin/gitea 2024/02/26 07:57:55 ...md/doctor_convert.go:33:runDoctorConvert() [I] AppWorkPath: /data/gitea 2024/02/26 07:57:55 ...md/doctor_convert.go:34:runDoctorConvert() [I] Custom path: /data/gitea 2024/02/26 07:57:55 ...md/doctor_convert.go:35:runDoctorConvert() [I] Log path: /data/gitea/log 2024/02/26 07:57:55 ...md/doctor_convert.go:36:runDoctorConvert() [I] Configuration file: /data/gitea/conf/app.ini 2024/02/26 07:57:55 cmd/main.go:117:func1() [I] [SQL] SELECT 'ALTER TABLE ' + OBJECT_NAME(SC.object_id) + ' MODIFY SC.name NVARCHAR(' + CONVERT(VARCHAR(5),SC.max_length) + ')' FROM SYS.columns SC JOIN SYS.types ST ON SC.system_type_id = ST.system_type_id AND SC.user_type_id = ST.user_type_id WHERE ST.name ='varchar' [] - 56.781156ms 2024/02/26 07:57:55 ...md/doctor_convert.go:47:runDoctorConvert() [F] Failed to convert database from varchar to nvarchar: mssql: Incorrect syntax near 'MODIFY'. 2024/02/26 07:57:55 cmd/main.go:117:func1() [I] [SQL] ALTER TABLE upload MODIFY SC.name NVARCHAR(40) [] - 4.071094ms
> 
> Version Gitea: 1.21.6

What's your mssql version?

**Comment by labronic** [comment]
Hi, 
my sql version is 2017

**Comment by lunny** [comment]
I think this should be resolved by #29238

**Comment by wxiaoguang** [comment]
> I think this should be resolved by #29238

It is not really resolved. Site admin needs to manually convert their database tables/columns to the same collation. There is not builtin tool in Gitea to do the converting.

**Comment by lunny** [comment]
I think this can be resolved by manually converting the collebrations.
