### ISSUE TITLE
(CI) Can't use matrix variable in `jobs.<job_id>.name`

### ISSUE THREAD

**Issue by TheBrokenRail** [go-gitea/gitea#28207]
### Description

I'm using a matrix in my Gitea Actions workflow, and I'm using matrix variables in the job's name, so it looks pretty in the UI. But Gitea doesn't substitute the variables.

```yaml
jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                mode:
                  - Client
                  - Server
                arch:
                  - AMD64
                  - ARM64
                  - ARMHF
        name: ${{ matrix.mode }} (${{ matrix.arch }})
```

Here's how I expected to work: https://futurestud.io/tutorials/github-actions-customize-the-job-name

### Gitea Version

v1.21.0

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![Screenshot from 2023-11-24 18-43-28](https://github.com/go-gitea/gitea/assets/17478432/c25dbe3e-f93f-4f14-a0cc-66683be32f22)

### How are you running Gitea?

Docker

### Database

None

**Comment by lunny** [comment]
Should be fixed by https://gitea.com/gitea/act/pulls/106

**Comment by kroltan** [comment]
Sorry to ping this issue, couldn't find a changelog for act_runner.

Is this available in any version? Gitea 1.22.4 / act_runner 0.2.11, I still see non interpolated text in the job names:

![2024-12-07_10-25](https://github.com/user-attachments/assets/e1b990c6-1017-4b99-96fa-2d8e8643adb2)

**Comment by ghnp5** [comment]
Just got the same problem here.

<img width="1260" height="334" alt="Image" src="https://github.com/user-attachments/assets/3a41441a-9841-4d44-b434-2924bb6eb077" />

```
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Flush Database
            script: /usr/bin/php /opt/app/...

    steps:
      - name: ${{ matrix.name }}
        uses: https://...
        with:
          host: ....myapp.com
          script: ${{ matrix.script }}
```

It's interesting that the name appears in the sidebar and in the upper title, but the step name itself got `${{ matrix.name }}`.

**Comment by bircni** [comment]
This was implemented and added with Gitea 1.27
