### ISSUE TITLE
Commit history overflow in issue page

### ISSUE THREAD

**Issue by yp05327** [go-gitea/gitea#30493]
### Description

![image](https://github.com/go-gitea/gitea/assets/18380374/74cbbd92-e6a6-4413-88d3-0fe27a529699)

### Gitea Version

latest

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

build

### Database

None

**Comment by silverwind** [comment]
Maybe https://github.com/go-gitea/gitea/pull/30484 has fixed it.

**Comment by silverwind** [comment]
That PR fixed another event type, but chances are this one here was fixed as well with it.

**Comment by yp05327** [comment]
Tested in `1.23.0+dev-104-gf9fdac9809` which contains #30484, it is not fixed.
