### ISSUE TITLE
Wrong link when search for organisation repositories

### ISSUE THREAD

**Issue by ggeant** [go-gitea/gitea#3148]
I'm relatively new to gitea, so I don't know if it's a bug, but it seems so to me.

When I'm on my profile page where you can search for the repositories (`/[username]`, the search goes over your repositories as well as organisational repositories that you are a part of.

However, when I click on a repository of an organisation, the url that is called always assumes that I am the owner, so it creates something like `/[username]/[repo]` instead of `/[organisation]/[repo]`.

This behaviour leads to a 404 page.

![gitea_profile](https://user-images.githubusercontent.com/30626354/33826018-db7ac5f4-de63-11e7-9efc-acc8f0a11a77.png)

![gitea_404](https://user-images.githubusercontent.com/30626354/33826025-e4728e58-de63-11e7-9f14-dd4e36313853.png)

**Comment by lafriks** [comment]
What gitea version you are using?

**Comment by ggeant** [comment]
1.3.0 was installed last week. Couldn't find it in the release notes though.

**Comment by ethantkoenig** [comment]
This has been fixed by https://github.com/go-gitea/gitea/pull/3093, but has not been backported to 1.3

**Comment by lunny** [comment]
resolved by #3093

**Comment by ggeant** [comment]
Unfortunately, #3093 does not resolve this issue. We upgraded to GiTea 1.3.1 last night, but the 404 page still persists when searching for organizational repositories.

**Comment by lafriks** [comment]
@ggeant it will be fixed in 1.3.2
