### ISSUE TITLE
failed: memcache: cache miss

### ISSUE THREAD

**Issue by somera** [go-gitea/gitea#31757]
### Description

I see this

```
2024/08/01 00:33:47 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[24099:main] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e6b0fc)
        /source/services/actions/commit_status.go:126 (0x1e7f83a)
        /source/services/actions/commit_status.go:28 (0x1e7ec7e)
        /source/services/actions/clear_tasks.go:97 (0x1e7e9ef)
        /source/services/cron/tasks_actions.go:50 (0x2541c3c)
        /source/services/cron/tasks.go:111 (0x253e7c7)
        /source/modules/graceful/manager.go:92 (0xaa98c6)
        /source/services/cron/tasks.go:88 (0x253e53a)
        /source/services/cron/tasks.go:67 (0x2543093)
        /usr/local/go/src/reflect/value.go:596 (0x4fccc5)
                Value.call: call(frametype, fn, stackArgs, uint32(frametype.Size()), uint32(abid.retOffset), uint32(frameSize), &regArgs)
        /usr/local/go/src/reflect/value.go:380 (0x4fbdd8)
                Value.Call: return v.call("Call", in)
        /go/pkg/mod/github.com/go-co-op/gocron@v1.37.0/gocron.go:122 (0x251fc04)
        /go/pkg/mod/github.com/go-co-op/gocron@v1.37.0/executor.go:87 (0x251de31)
        /go/pkg/mod/github.com/go-co-op/gocron@v1.37.0/executor.go:213 (0x251eb17)
        /go/pkg/mod/github.com/go-co-op/gocron@v1.37.0/executor.go:269 (0x251f5b7)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP
```

exception often in gitea.log. And I have no idea if somethis is now slow or not.

Any I have an memcached instance.

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.46.0

### Operating System

Ubuntu 22.04.x LTS x86_64

### How are you running Gitea?

Downloaded gitea-1.22.1-linux-amd64

### Database

PostgreSQL

**Comment by somera** [comment]
Is this
```
2024/08/01 22:36:57 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:57 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:58 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:58 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:58 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
2024/08/01 22:36:58 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13953025034712252310 18263062709511 0x6a1a080} false}
```
the result of the exception?

**Comment by somera** [comment]
In the last 12 days:
```
$ zgrep "memcache: cache miss" gitea.log* | wc -l
373
```

**Comment by lunny** [comment]
duplicated #31102 and this should be fixed by 1.22.1

**Comment by somera** [comment]
@lunny I see this exception in my current gitea.log 1.22.1. Looks like this is not fixed.

**Comment by somera** [comment]
In #31102 I couln'd start my gitea. The bug was fixed, but now I see this exception.

**Comment by lunny** [comment]
Can you give more logs? What were the operations when the logs was recorded?

**Comment by somera** [comment]
I enabled not Info logging. If I see this error in the next days than I can post more details.

**Comment by somera** [comment]
With Info level I don't have not so much output. But I saw this

```
2024/08/02 00:32:41 ...irror/mirror_pull.go:178:parseRemoteUpdateOutput() [W] parseRemoteUpdateOutput: unexpected update line " * [new ref]           refs/pull/1454/head  -> refs/pull/1454/head"
2024/08/02 00:32:41 ...irror/mirror_pull.go:178:parseRemoteUpdateOutput() [W] parseRemoteUpdateOutput: unexpected update line " * [new ref]           refs/pull/1456/head  -> refs/pull/1456/head"
2024/08/02 00:32:41 ...irror/mirror_pull.go:178:parseRemoteUpdateOutput() [W] parseRemoteUpdateOutput: unexpected update line " * [new ref]           refs/pull/1456/merge -> refs/pull/1456/merge"
2024/08/02 00:32:41 ...irror/mirror_pull.go:178:parseRemoteUpdateOutput() [W] parseRemoteUpdateOutput: unexpected update line " * [new ref]           refs/pull/1457/head  -> refs/pull/1457/head"
2024/08/02 00:32:41 ...irror/mirror_pull.go:178:parseRemoteUpdateOutput() [W] parseRemoteUpdateOutput: unexpected update line " * [new ref]           refs/pull/1457/merge -> refs/pull/1457/merge"
2024/08/02 00:32:41 ...actions/workflows.go:121:DetectWorkflows() [W] ignore invalid workflow "npm-release.yml": unknown on type: map[string]interface {}{"node-version":map[string]interface {}{"required":true, "type":"string"}, "release-directory":map[string]interface {}{"default":"./", "type":"string"}, "require-build":map[string]interface {}{"default":true, "type":"string"}}
2024/08/02 00:32:41 ...actions/workflows.go:121:DetectWorkflows() [W] ignore invalid workflow "npm-release.yml": unknown on type: map[string]interface {}{"node-version":map[string]interface {}{"required":true, "type":"string"}, "release-directory":map[string]interface {}{"default":"./", "type":"string"}, "require-build":map[string]interface {}{"default":true, "type":"string"}}
2024/08/02 00:32:41 ...actions/workflows.go:121:DetectWorkflows() [W] ignore invalid workflow "npm-release.yml": unknown on type: map[string]interface {}{"node-version":map[string]interface {}{"required":true, "type":"string"}, "release-directory":map[string]interface {}{"default":"./", "type":"string"}, "require-build":map[string]interface {}{"default":true, "type":"string"}}
2024/08/02 00:32:41 ...actions/workflows.go:121:DetectWorkflows() [W] ignore invalid workflow "npm-release.yml": unknown on type: map[string]interface {}{"github-token":map[string]interface {}{"required":true}, "npm-token":map[string]interface {}{"required":true}}
2024/08/02 00:32:41 ...actions/workflows.go:121:DetectWorkflows() [W] ignore invalid workflow "npm-release.yml": unknown on type: map[string]interface {}{"node-version":map[string]interface {}{"required":true, "type":"string"}, "release-directory":map[string]interface {}{"default":"./", "type":"string"}, "require-build":map[string]interface {}{"default":true, "type":"string"}}
2024/08/02 00:32:41 ...actions/workflows.go:121:DetectWorkflows() [W] ignore invalid workflow "npm-release.yml": unknown on type: map[string]interface {}{"node-version":map[string]interface {}{"required":true, "type":"string"}, "release-directory":map[string]interface {}{"default":"./", "type":"string"}, "require-build":map[string]interface {}{"default":true, "type":"string"}}
2024/08/02 00:32:41 ...actions/workflows.go:121:DetectWorkflows() [W] ignore invalid workflow "npm-release.yml": unknown on type: map[string]interface {}{"node-version":map[string]interface {}{"required":true, "type":"string"}, "release-directory":map[string]interface {}{"default":"./", "type":"string"}, "require-build":map[string]interface {}{"default":true, "type":"string"}}
2024/08/02 00:32:41 ...actions/workflows.go:121:DetectWorkflows() [W] ignore invalid workflow "npm-release.yml": unknown on type: map[string]interface {}{"node-version":map[string]interface {}{"required":true, "type":"string"}, "release-directory":map[string]interface {}{"default":"./", "type":"string"}, "require-build":map[string]interface {}{"default":true, "type":"string"}}
2024/08/02 00:32:41 ...actions/workflows.go:121:DetectWorkflows() [W] ignore invalid workflow "npm-release.yml": unknown on type: map[string]interface {}{"node-version":map[string]interface {}{"required":true, "type":"string"}, "release-directory":map[string]interface {}{"default":"./", "type":"string"}, "require-build":map[string]interface {}{"default":true, "type":"string"}}
2024/08/02 00:32:42 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[24361:master] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e6b0fc)
        /source/services/actions/commit_status.go:126 (0x1e7f83a)
        /source/services/actions/commit_status.go:28 (0x1e7ec7e)
        /source/services/actions/notifier_helper.go:351 (0x1e89d74)
        /source/services/actions/notifier_helper.go:228 (0x1e88cd4)
        /source/services/actions/notifier_helper.go:112 (0x1e87a5b)
        /source/services/actions/notifier.go:608 (0x1e85e73)
        /source/services/notify/notify.go:325 (0x2531fcb)
        /source/services/mirror/mirror_pull.go:535 (0x2531b9a)
        /source/services/mirror/mirror.go:27 (0x2528ee9)
        /source/services/mirror/mirror.go:124 (0x252985d)
        /source/modules/queue/workerqueue.go:246 (0x1eb97c9)
        /source/modules/queue/workergroup.go:103 (0x1c44162)
        /source/modules/queue/workergroup.go:178 (0x1eb7f24)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/08/02 00:32:42 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[24361:master] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e6b0fc)
        /source/services/actions/commit_status.go:126 (0x1e7f83a)
        /source/services/actions/commit_status.go:28 (0x1e7ec7e)
        /source/services/actions/notifier_helper.go:351 (0x1e89d74)
        /source/services/actions/notifier_helper.go:228 (0x1e88cd4)
        /source/services/actions/notifier_helper.go:112 (0x1e87a5b)
        /source/services/actions/notifier.go:608 (0x1e85e73)
        /source/services/notify/notify.go:325 (0x2531fcb)
        /source/services/mirror/mirror_pull.go:535 (0x2531b9a)
        /source/services/mirror/mirror.go:27 (0x2528ee9)
        /source/services/mirror/mirror.go:124 (0x252985d)
        /source/modules/queue/workerqueue.go:246 (0x1eb97c9)
        /source/modules/queue/workergroup.go:103 (0x1c44162)
        /source/modules/queue/workergroup.go:178 (0x1eb7f24)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/08/02 00:32:42 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[24361:master] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e6b0fc)
        /source/services/actions/commit_status.go:126 (0x1e7f83a)
        /source/services/actions/commit_status.go:28 (0x1e7ec7e)
        /source/services/actions/notifier_helper.go:351 (0x1e89d74)
        /source/services/actions/notifier_helper.go:228 (0x1e88cd4)
        /source/services/actions/notifier_helper.go:112 (0x1e87a5b)
        /source/services/actions/notifier.go:608 (0x1e85e73)
        /source/services/notify/notify.go:325 (0x2531fcb)
        /source/services/mirror/mirror_pull.go:535 (0x2531b9a)
        /source/services/mirror/mirror.go:27 (0x2528ee9)
        /source/services/mirror/mirror.go:124 (0x252985d)
        /source/modules/queue/workerqueue.go:246 (0x1eb97c9)
        /source/modules/queue/workergroup.go:103 (0x1c44162)
        /source/modules/queue/workergroup.go:178 (0x1eb7f24)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/08/02 00:32:42 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[24361:master] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e6b0fc)
        /source/services/actions/commit_status.go:126 (0x1e7f83a)
        /source/services/actions/commit_status.go:28 (0x1e7ec7e)
        /source/services/actions/notifier_helper.go:351 (0x1e89d74)
        /source/services/actions/notifier_helper.go:228 (0x1e88cd4)
        /source/services/actions/notifier_helper.go:112 (0x1e87a5b)
        /source/services/actions/notifier.go:608 (0x1e85e73)
        /source/services/notify/notify.go:325 (0x2531fcb)
        /source/services/mirror/mirror_pull.go:535 (0x2531b9a)
        /source/services/mirror/mirror.go:27 (0x2528ee9)
        /source/services/mirror/mirror.go:124 (0x252985d)
        /source/modules/queue/workerqueue.go:246 (0x1eb97c9)
        /source/modules/queue/workergroup.go:103 (0x1c44162)
        /source/modules/queue/workergroup.go:178 (0x1eb7f24)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/08/02 00:32:42 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[24361:master] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e6b0fc)
        /source/services/actions/commit_status.go:126 (0x1e7f83a)
        /source/services/actions/commit_status.go:28 (0x1e7ec7e)
        /source/services/actions/notifier_helper.go:351 (0x1e89d74)
        /source/services/actions/notifier_helper.go:228 (0x1e88cd4)
        /source/services/actions/notifier_helper.go:112 (0x1e87a5b)
        /source/services/actions/notifier.go:608 (0x1e85e73)
        /source/services/notify/notify.go:325 (0x2531fcb)
        /source/services/mirror/mirror_pull.go:535 (0x2531b9a)
        /source/services/mirror/mirror.go:27 (0x2528ee9)
        /source/services/mirror/mirror.go:124 (0x252985d)
        /source/modules/queue/workerqueue.go:246 (0x1eb97c9)
        /source/modules/queue/workergroup.go:103 (0x1c44162)
        /source/modules/queue/workergroup.go:178 (0x1eb7f24)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/08/02 00:32:42 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[24361:master] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e6b0fc)
        /source/services/actions/commit_status.go:126 (0x1e7f83a)
        /source/services/actions/commit_status.go:28 (0x1e7ec7e)
        /source/services/actions/notifier_helper.go:351 (0x1e89d74)
        /source/services/actions/notifier_helper.go:228 (0x1e88cd4)
        /source/services/actions/notifier_helper.go:112 (0x1e87a5b)
        /source/services/actions/notifier.go:608 (0x1e85e73)
        /source/services/notify/notify.go:325 (0x2531fcb)
        /source/services/mirror/mirror_pull.go:535 (0x2531b9a)
        /source/services/mirror/mirror.go:27 (0x2528ee9)
        /source/services/mirror/mirror.go:124 (0x252985d)
        /source/modules/queue/workerqueue.go:246 (0x1eb97c9)
        /source/modules/queue/workergroup.go:103 (0x1c44162)
        /source/modules/queue/workergroup.go:178 (0x1eb7f24)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/08/02 00:32:42 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[24361:master] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e6b0fc)
        /source/services/actions/commit_status.go:126 (0x1e7f83a)
        /source/services/actions/commit_status.go:28 (0x1e7ec7e)
        /source/services/actions/notifier_helper.go:351 (0x1e89d74)
        /source/services/actions/notifier_helper.go:228 (0x1e88cd4)
        /source/services/actions/notifier_helper.go:112 (0x1e87a5b)
        /source/services/actions/notifier.go:608 (0x1e85e73)
        /source/services/notify/notify.go:325 (0x2531fcb)
        /source/services/mirror/mirror_pull.go:535 (0x2531b9a)
        /source/services/mirror/mirror.go:27 (0x2528ee9)
        /source/services/mirror/mirror.go:124 (0x252985d)
        /source/modules/queue/workerqueue.go:246 (0x1eb97c9)
        /source/modules/queue/workergroup.go:103 (0x1c44162)
        /source/modules/queue/workergroup.go:178 (0x1eb7f24)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/08/02 00:32:42 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[24361:master] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e6b0fc)
        /source/services/actions/commit_status.go:126 (0x1e7f83a)
        /source/services/actions/commit_status.go:28 (0x1e7ec7e)
        /source/services/actions/notifier_helper.go:351 (0x1e89d74)
        /source/services/actions/notifier_helper.go:228 (0x1e88cd4)
        /source/services/actions/notifier_helper.go:112 (0x1e87a5b)
        /source/services/actions/notifier.go:608 (0x1e85e73)
        /source/services/notify/notify.go:325 (0x2531fcb)
        /source/services/mirror/mirror_pull.go:535 (0x2531b9a)
        /source/services/mirror/mirror.go:27 (0x2528ee9)
        /source/services/mirror/mirror.go:124 (0x252985d)
        /source/modules/queue/workerqueue.go:246 (0x1eb97c9)
        /source/modules/queue/workergroup.go:103 (0x1c44162)
        /source/modules/queue/workergroup.go:178 (0x1eb7f24)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/08/02 00:32:42 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[24361:master] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e6b0fc)
        /source/services/actions/commit_status.go:126 (0x1e7f83a)
        /source/services/actions/commit_status.go:28 (0x1e7ec7e)
        /source/services/actions/notifier_helper.go:351 (0x1e89d74)
        /source/services/actions/notifier_helper.go:228 (0x1e88cd4)
        /source/services/actions/notifier_helper.go:112 (0x1e87a5b)
        /source/services/actions/notifier.go:608 (0x1e85e73)
        /source/services/notify/notify.go:325 (0x2531fcb)
        /source/services/mirror/mirror_pull.go:535 (0x2531b9a)
        /source/services/mirror/mirror.go:27 (0x2528ee9)
        /source/services/mirror/mirror.go:124 (0x252985d)
        /source/modules/queue/workerqueue.go:246 (0x1eb97c9)
        /source/modules/queue/workergroup.go:103 (0x1c44162)
        /source/modules/queue/workergroup.go:178 (0x1eb7f24)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/08/02 00:32:42 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[24361:master] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e6b0fc)
        /source/services/actions/commit_status.go:126 (0x1e7f83a)
        /source/services/actions/commit_status.go:28 (0x1e7ec7e)
        /source/services/actions/notifier_helper.go:351 (0x1e89d74)
        /source/services/actions/notifier_helper.go:228 (0x1e88cd4)
        /source/services/actions/notifier_helper.go:112 (0x1e87a5b)
        /source/services/actions/notifier.go:608 (0x1e85e73)
        /source/services/notify/notify.go:325 (0x2531fcb)
        /source/services/mirror/mirror_pull.go:535 (0x2531b9a)
        /source/services/mirror/mirror.go:27 (0x2528ee9)
        /source/services/mirror/mirror.go:124 (0x252985d)
        /source/modules/queue/workerqueue.go:246 (0x1eb97c9)
        /source/modules/queue/workergroup.go:103 (0x1c44162)
        /source/modules/queue/workergroup.go:178 (0x1eb7f24)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/08/02 00:32:42 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[24361:master] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e6b0fc)
        /source/services/actions/commit_status.go:126 (0x1e7f83a)
        /source/services/actions/commit_status.go:28 (0x1e7ec7e)
        /source/services/actions/notifier_helper.go:351 (0x1e89d74)
        /source/services/actions/notifier_helper.go:228 (0x1e88cd4)
        /source/services/actions/notifier_helper.go:112 (0x1e87a5b)
        /source/services/actions/notifier.go:608 (0x1e85e73)
        /source/services/notify/notify.go:325 (0x2531fcb)
        /source/services/mirror/mirror_pull.go:535 (0x2531b9a)
        /source/services/mirror/mirror.go:27 (0x2528ee9)
        /source/services/mirror/mirror.go:124 (0x252985d)
        /source/modules/queue/workerqueue.go:246 (0x1eb97c9)
        /source/modules/queue/workergroup.go:103 (0x1c44162)
        /source/modules/queue/workergroup.go:178 (0x1eb7f24)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/08/02 00:32:42 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[24361:master] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e6b0fc)
        /source/services/actions/commit_status.go:126 (0x1e7f83a)
        /source/services/actions/commit_status.go:28 (0x1e7ec7e)
        /source/services/actions/notifier_helper.go:351 (0x1e89d74)
        /source/services/actions/notifier_helper.go:228 (0x1e88cd4)
        /source/services/actions/notifier_helper.go:112 (0x1e87a5b)
        /source/services/actions/notifier.go:608 (0x1e85e73)
        /source/services/notify/notify.go:325 (0x2531fcb)
        /source/services/mirror/mirror_pull.go:535 (0x2531b9a)
        /source/services/mirror/mirror.go:27 (0x2528ee9)
        /source/services/mirror/mirror.go:124 (0x252985d)
        /source/modules/queue/workerqueue.go:246 (0x1eb97c9)
        /source/modules/queue/workergroup.go:103 (0x1c44162)
        /source/modules/queue/workergroup.go:178 (0x1eb7f24)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/08/02 00:32:42 ...s/notifier_helper.go:113:Notify() [E] an error occurred while executing the SyncPushCommits actions method: gitRepo.GetCommit: object does not exist [id: refs/heads/refs/pull/1443/merge, rel_path: ]
        /source/services/actions/notifier_helper.go:113 (0x1e87a73)
        /source/services/actions/notifier.go:608 (0x1e85e73)
        /source/services/notify/notify.go:325 (0x2531fcb)
        /source/services/mirror/mirror_pull.go:535 (0x2531b9a)
        /source/services/mirror/mirror.go:27 (0x2528ee9)
        /source/services/mirror/mirror.go:124 (0x252985d)
        /source/modules/queue/workerqueue.go:246 (0x1eb97c9)
        /source/modules/queue/workergroup.go:103 (0x1c44162)
        /source/modules/queue/workergroup.go:178 (0x1eb7f24)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/08/02 00:32:42 ...s/notifier_helper.go:113:Notify() [E] an error occurred while executing the SyncPushCommits actions method: gitRepo.GetCommit: object does not exist [id: refs/heads/refs/pull/1445/merge, rel_path: ]
        /source/services/actions/notifier_helper.go:113 (0x1e87a73)
        /source/services/actions/notifier.go:608 (0x1e85e73)
        /source/services/notify/notify.go:325 (0x2531fcb)
        /source/services/mirror/mirror_pull.go:535 (0x2531b9a)
        /source/services/mirror/mirror.go:27 (0x2528ee9)
        /source/services/mirror/mirror.go:124 (0x252985d)
        /source/modules/queue/workerqueue.go:246 (0x1eb97c9)
        /source/modules/queue/workergroup.go:103 (0x1c44162)
        /source/modules/queue/workergroup.go:178 (0x1eb7f24)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP
```

during update mirrors.

**Comment by somera** [comment]
@lunny is this ok?

[gitea.log](https://github.com/user-attachments/files/16462461/gitea.log)

At the end you will see a lot of error. All during update mirrors task.

**Comment by somera** [comment]
@lunny here with debug level

```
2024/08/02 01:01:52 ...dules/git/command.go:291:Run() [D] git.Command.RunDir(/var/lib/gitea/repositories/psf/pyperf.git): /usr/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= rev-parse
2024/08/02 01:01:52 ...dules/git/command.go:291:Run() [D] git.Command.RunDir(/var/lib/gitea/repositories/psf/pyperf.git): /usr/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= cat-file --batch
2024/08/02 01:01:52 ...dules/git/command.go:291:Run() [D] git.Command.RunDir(/var/lib/gitea/repositories/psf/pyperf.git): /usr/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= cat-file --batch-check
2024/08/02 01:01:52 ...dules/git/command.go:291:Run() [D] git.Command.RunDir(/var/lib/gitea/repositories/psf/pyperf.git): /usr/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= hash-object --stdin
2024/08/02 01:01:52 ...git/commit_status.go:450:NewCommitStatus() [D] NewCommitStatus[/var/lib/gitea/repositories/psf/pyperf.git, c6c33d9db2f298b9fde575361055643912551cf1]: 11
2024/08/02 01:01:52 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[24543:main] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e6b0fc)
        /source/services/actions/commit_status.go:126 (0x1e7f83a)
        /source/services/actions/commit_status.go:28 (0x1e7ec7e)
        /source/services/actions/notifier_helper.go:351 (0x1e89d74)
        /source/services/actions/notifier_helper.go:228 (0x1e88cd4)
        /source/services/actions/notifier_helper.go:112 (0x1e87a5b)
        /source/services/actions/notifier.go:608 (0x1e85e73)
        /source/services/notify/notify.go:325 (0x2531fcb)
        /source/services/mirror/mirror_pull.go:535 (0x2531b9a)
        /source/services/mirror/mirror.go:27 (0x2528ee9)
        /source/services/mirror/mirror.go:124 (0x252985d)
        /source/modules/queue/workerqueue.go:246 (0x1eb97c9)
        /source/modules/queue/workergroup.go:103 (0x1c44162)
        /source/modules/queue/workergroup.go:178 (0x1eb7f24)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/08/02 01:01:52 ...dules/git/command.go:291:Run() [D] git.Command.RunDir(/var/lib/gitea/repositories/psf/pyperf.git): /usr/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= rev-parse
2024/08/02 01:01:52 ...dules/git/command.go:291:Run() [D] git.Command.RunDir(/var/lib/gitea/repositories/psf/pyperf.git): /usr/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= cat-file --batch
2024/08/02 01:01:52 ...dules/git/command.go:291:Run() [D] git.Command.RunDir(/var/lib/gitea/repositories/psf/pyperf.git): /usr/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= cat-file --batch-check
2024/08/02 01:01:52 ...dules/git/command.go:291:Run() [D] git.Command.RunDir(/var/lib/gitea/repositories/psf/pyperf.git): /usr/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= hash-object --stdin
2024/08/02 01:01:52 ...git/commit_status.go:450:NewCommitStatus() [D] NewCommitStatus[/var/lib/gitea/repositories/psf/pyperf.git, c6c33d9db2f298b9fde575361055643912551cf1]: 12
2024/08/02 01:01:52 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[24543:main] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e6b0fc)
        /source/services/actions/commit_status.go:126 (0x1e7f83a)
        /source/services/actions/commit_status.go:28 (0x1e7ec7e)
        /source/services/actions/notifier_helper.go:351 (0x1e89d74)
        /source/services/actions/notifier_helper.go:228 (0x1e88cd4)
        /source/services/actions/notifier_helper.go:112 (0x1e87a5b)
        /source/services/actions/notifier.go:608 (0x1e85e73)
        /source/services/notify/notify.go:325 (0x2531fcb)
        /source/services/mirror/mirror_pull.go:535 (0x2531b9a)
        /source/services/mirror/mirror.go:27 (0x2528ee9)
        /source/services/mirror/mirror.go:124 (0x252985d)
        /source/modules/queue/workerqueue.go:246 (0x1eb97c9)
        /source/modules/queue/workergroup.go:103 (0x1c44162)
        /source/modules/queue/workergroup.go:178 (0x1eb7f24)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/08/02 01:01:52 ...dules/git/command.go:291:Run() [D] git.Command.RunDir(/var/lib/gitea/repositories/psf/pyperf.git): /usr/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= rev-parse
2024/08/02 01:01:52 ...dules/git/command.go:291:Run() [D] git.Command.RunDir(/var/lib/gitea/repositories/psf/pyperf.git): /usr/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= cat-file --batch
2024/08/02 01:01:52 ...dules/git/command.go:291:Run() [D] git.Command.RunDir(/var/lib/gitea/repositories/psf/pyperf.git): /usr/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= cat-file --batch-check
2024/08/02 01:01:52 ...dules/git/command.go:291:Run() [D] git.Command.RunDir(/var/lib/gitea/repositories/psf/pyperf.git): /usr/bin/git -c protocol.version=2 -c credential.helper= -c filter.lfs.required= -c filter.lfs.smudge= -c filter.lfs.clean= hash-object --stdin
2024/08/02 01:01:52 ...git/commit_status.go:450:NewCommitStatus() [D] NewCommitStatus[/var/lib/gitea/repositories/psf/pyperf.git, c6c33d9db2f298b9fde575361055643912551cf1]: 13
2024/08/02 01:01:52 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[24543:main] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e6b0fc)
        /source/services/actions/commit_status.go:126 (0x1e7f83a)
        /source/services/actions/commit_status.go:28 (0x1e7ec7e)
        /source/services/actions/notifier_helper.go:351 (0x1e89d74)
        /source/services/actions/notifier_helper.go:228 (0x1e88cd4)
        /source/services/actions/notifier_helper.go:112 (0x1e87a5b)
        /source/services/actions/notifier.go:608 (0x1e85e73)
        /source/services/notify/notify.go:325 (0x2531fcb)
        /source/services/mirror/mirror_pull.go:535 (0x2531b9a)
        /source/services/mirror/mirror.go:27 (0x2528ee9)
        /source/services/mirror/mirror.go:124 (0x252985d)
        /source/modules/queue/workerqueue.go:246 (0x1eb97c9)
        /source/modules/queue/workergroup.go:103 (0x1c44162)
        /source/modules/queue/workergroup.go:178 (0x1eb7f24)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP
```

But take a look into the gitea.log. Cause there you see other exceptions.

**Comment by somera** [comment]
@lunny was this helpful?

**Comment by lunny** [comment]
> @lunny was this helpful?

Thank you very much. I will look into them.

**Comment by somera** [comment]
@lunny how is the status here?

**Comment by lunny** [comment]
This logs is not a real error and can be ignored. It will be logged as error because deleting a cache key but the key doesn't exist. Since cache is an interface and memcache library returned `ErrCacheMiss` and different cache returned error. It's not easy to catch the key not found error to ignore.

**Comment by lunny** [comment]
Another error
```log
notifier_helper.go:113:Notify() [E] an error occurred while executing the SyncPushCommits actions method: gitRepo.GetCommit: object does not exist [id: refs/heads/refs/pull/49/head, rel_path: ]
        /source/services/actions/notifier_helper.go:113 (0x1e87a73)
        /source/services/actions/notifier.go:608 (0x1e85e73)
        /source/services/notify/notify.go:325 (0x2531fcb)
        /source/services/mirror/mirror_pull.go:535 (0x2531b9a)
        /source/services/mirror/mirror.go:27 (0x2528ee9)
        /source/services/mirror/mirror.go:124 (0x252985d)
        /source/modules/queue/workerqueue.go:246 (0x1eb97c9)
        /source/modules/queue/workergroup.go:103 (0x1c44162)
        /source/modules/queue/workergroup.go:178 (0x1eb7f24)
```
Looks like a bug.

**Comment by somera** [comment]
What are the consequences of the error?

**Comment by lunny** [comment]
The first error will not any effection for usage. The second will not trigger actions for mirror sync.

**Comment by somera** [comment]
I have 1120 log entries with this error in last 7 days.
```
$ zgrep "an error occurred while executing the SyncPushCommits" gitea.log* | grep -o '\[[^]]*\]' | sed 's/[\[\]]//g' | awk 'length($0)>3' | sort | uniq | wc -l
1120
```
Will this be fixed for the next release?

**Comment by lunny** [comment]
@somera Can you upgrade to 1.22.2 to confirm is this fixed for you?

**Comment by somera** [comment]
@lunny I updated yesterday. I will take a look into logs in the next days.

**Comment by somera** [comment]
@lunny on slow pages I see whis
```
2024/09/06 19:56:48 ...activities/action.go:461:GetFeeds() [W] [Slow SQL Query] SELECT "action".* FROM "action" INNER JOIN "repository" ON "repository".id = "action".repo_id WHERE user_id=$1 AND is_deleted=$2 ORDER BY "action"."created_unix" DESC LIMIT 20 OFFSET 1910700 [1 false] - 9.95783878s
2024/09/06 19:56:50 ...activities/action.go:461:GetFeeds() [W] [Slow SQL Query] SELECT count(*) FROM "action" INNER JOIN "repository" ON "repository".id = "action".repo_id WHERE user_id=$1 AND is_deleted=$2 [1 false] - 1.63526821s
2024/09/06 19:56:50 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:50 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:51 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:51 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:51 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:51 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:51 ...les/cache/context.go:134:GetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:51 ...les/cache/context.go:147:SetContextData() [W] cache context is expired, may be misused for long-life tasks: &{map[] {{0 0} 0 0 {{} 0} {{} 0}} {13956354484237509102 85424598204433 0x6a66660} false}
2024/09/06 19:56:51 ...eb/routing/logger.go:102:func1() [I] router: completed GET /?page=95536&date= for 192.168.178.21:0, 200 OK in 12629.5ms @ web/home.go:32(web.Home)
```
warnings.

**Comment by lunny** [comment]
OK. Maybe it could be another issue. And I will take a look at that next week.

**Comment by somera** [comment]
And now I habe this

```
2024/09/06 20:03:38 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[25782:main] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e9fa7c)
        /source/services/actions/commit_status.go:126 (0x1eb41ba)
        /source/services/actions/commit_status.go:28 (0x1eb35fe)
        /source/services/actions/notifier_helper.go:356 (0x1ebe8b4)
        /source/services/actions/notifier_helper.go:233 (0x1ebd7ea)
        /source/services/actions/notifier_helper.go:112 (0x1ebc3fb)
        /source/services/actions/notifier.go:608 (0x1eba813)
        /source/services/notify/notify.go:325 (0x2567c2b)
        /source/services/mirror/mirror_pull.go:535 (0x25677fa)
        /source/services/mirror/mirror.go:27 (0x255eb49)
        /source/services/mirror/mirror.go:124 (0x255f4bd)
        /source/modules/queue/workerqueue.go:246 (0x1eee7e9)
        /source/modules/queue/workergroup.go:103 (0x1c77982)
        /source/modules/queue/workergroup.go:178 (0x1eecf44)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/09/06 20:03:38 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[25782:main] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e9fa7c)
        /source/services/actions/commit_status.go:126 (0x1eb41ba)
        /source/services/actions/commit_status.go:28 (0x1eb35fe)
        /source/services/actions/notifier_helper.go:356 (0x1ebe8b4)
        /source/services/actions/notifier_helper.go:233 (0x1ebd7ea)
        /source/services/actions/notifier_helper.go:112 (0x1ebc3fb)
        /source/services/actions/notifier.go:608 (0x1eba813)
        /source/services/notify/notify.go:325 (0x2567c2b)
        /source/services/mirror/mirror_pull.go:535 (0x25677fa)
        /source/services/mirror/mirror.go:27 (0x255eb49)
        /source/services/mirror/mirror.go:124 (0x255f4bd)
        /source/modules/queue/workerqueue.go:246 (0x1eee7e9)
        /source/modules/queue/workergroup.go:103 (0x1c77982)
        /source/modules/queue/workergroup.go:178 (0x1eecf44)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/09/06 20:03:38 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[25782:main] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e9fa7c)
        /source/services/actions/commit_status.go:126 (0x1eb41ba)
        /source/services/actions/commit_status.go:28 (0x1eb35fe)
        /source/services/actions/notifier_helper.go:356 (0x1ebe8b4)
        /source/services/actions/notifier_helper.go:233 (0x1ebd7ea)
        /source/services/actions/notifier_helper.go:112 (0x1ebc3fb)
        /source/services/actions/notifier.go:608 (0x1eba813)
        /source/services/notify/notify.go:325 (0x2567c2b)
        /source/services/mirror/mirror_pull.go:535 (0x25677fa)
        /source/services/mirror/mirror.go:27 (0x255eb49)
        /source/services/mirror/mirror.go:124 (0x255f4bd)
        /source/modules/queue/workerqueue.go:246 (0x1eee7e9)
        /source/modules/queue/workergroup.go:103 (0x1c77982)
        /source/modules/queue/workergroup.go:178 (0x1eecf44)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/09/06 20:03:38 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[25782:main] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e9fa7c)
        /source/services/actions/commit_status.go:126 (0x1eb41ba)
        /source/services/actions/commit_status.go:28 (0x1eb35fe)
        /source/services/actions/notifier_helper.go:356 (0x1ebe8b4)
        /source/services/actions/notifier_helper.go:233 (0x1ebd7ea)
        /source/services/actions/notifier_helper.go:112 (0x1ebc3fb)
        /source/services/actions/notifier.go:608 (0x1eba813)
        /source/services/notify/notify.go:325 (0x2567c2b)
        /source/services/mirror/mirror_pull.go:535 (0x25677fa)
        /source/services/mirror/mirror.go:27 (0x255eb49)
        /source/services/mirror/mirror.go:124 (0x255f4bd)
        /source/modules/queue/workerqueue.go:246 (0x1eee7e9)
        /source/modules/queue/workergroup.go:103 (0x1c77982)
        /source/modules/queue/workergroup.go:178 (0x1eecf44)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/09/06 20:03:38 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[25782:main] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e9fa7c)
        /source/services/actions/commit_status.go:126 (0x1eb41ba)
        /source/services/actions/commit_status.go:28 (0x1eb35fe)
        /source/services/actions/notifier_helper.go:356 (0x1ebe8b4)
        /source/services/actions/notifier_helper.go:233 (0x1ebd7ea)
        /source/services/actions/notifier_helper.go:112 (0x1ebc3fb)
        /source/services/actions/notifier.go:608 (0x1eba813)
        /source/services/notify/notify.go:325 (0x2567c2b)
        /source/services/mirror/mirror_pull.go:535 (0x25677fa)
        /source/services/mirror/mirror.go:27 (0x255eb49)
        /source/services/mirror/mirror.go:124 (0x255f4bd)
        /source/modules/queue/workerqueue.go:246 (0x1eee7e9)
        /source/modules/queue/workergroup.go:103 (0x1c77982)
        /source/modules/queue/workergroup.go:178 (0x1eecf44)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/09/06 20:03:38 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[25782:main] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e9fa7c)
        /source/services/actions/commit_status.go:126 (0x1eb41ba)
        /source/services/actions/commit_status.go:28 (0x1eb35fe)
        /source/services/actions/notifier_helper.go:356 (0x1ebe8b4)
        /source/services/actions/notifier_helper.go:233 (0x1ebd7ea)
        /source/services/actions/notifier_helper.go:112 (0x1ebc3fb)
        /source/services/actions/notifier.go:608 (0x1eba813)
        /source/services/notify/notify.go:325 (0x2567c2b)
        /source/services/mirror/mirror_pull.go:535 (0x25677fa)
        /source/services/mirror/mirror.go:27 (0x255eb49)
        /source/services/mirror/mirror.go:124 (0x255f4bd)
        /source/modules/queue/workerqueue.go:246 (0x1eee7e9)
        /source/modules/queue/workergroup.go:103 (0x1c77982)
        /source/modules/queue/workergroup.go:178 (0x1eecf44)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/09/06 20:03:38 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[25782:main] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e9fa7c)
        /source/services/actions/commit_status.go:126 (0x1eb41ba)
        /source/services/actions/commit_status.go:28 (0x1eb35fe)
        /source/services/actions/notifier_helper.go:356 (0x1ebe8b4)
        /source/services/actions/notifier_helper.go:233 (0x1ebd7ea)
        /source/services/actions/notifier_helper.go:112 (0x1ebc3fb)
        /source/services/actions/notifier.go:608 (0x1eba813)
        /source/services/notify/notify.go:325 (0x2567c2b)
        /source/services/mirror/mirror_pull.go:535 (0x25677fa)
        /source/services/mirror/mirror.go:27 (0x255eb49)
        /source/services/mirror/mirror.go:124 (0x255f4bd)
        /source/modules/queue/workerqueue.go:246 (0x1eee7e9)
        /source/modules/queue/workergroup.go:103 (0x1c77982)
        /source/modules/queue/workergroup.go:178 (0x1eecf44)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/09/06 20:03:38 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[25782:main] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e9fa7c)
        /source/services/actions/commit_status.go:126 (0x1eb41ba)
        /source/services/actions/commit_status.go:28 (0x1eb35fe)
        /source/services/actions/notifier_helper.go:356 (0x1ebe8b4)
        /source/services/actions/notifier_helper.go:233 (0x1ebd7ea)
        /source/services/actions/notifier_helper.go:112 (0x1ebc3fb)
        /source/services/actions/notifier.go:608 (0x1eba813)
        /source/services/notify/notify.go:325 (0x2567c2b)
        /source/services/mirror/mirror_pull.go:535 (0x25677fa)
        /source/services/mirror/mirror.go:27 (0x255eb49)
        /source/services/mirror/mirror.go:124 (0x255f4bd)
        /source/modules/queue/workerqueue.go:246 (0x1eee7e9)
        /source/modules/queue/workergroup.go:103 (0x1c77982)
        /source/modules/queue/workergroup.go:178 (0x1eecf44)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP


2024/09/06 20:03:38 ...atus/commitstatus.go:113:CreateCommitStatus() [E] deleteCommitStatusCache[25782:main] failed: memcache: cache miss
        /source/services/repository/commitstatus/commitstatus.go:113 (0x1e9fa7c)
        /source/services/actions/commit_status.go:126 (0x1eb41ba)
        /source/services/actions/commit_status.go:28 (0x1eb35fe)
        /source/services/actions/notifier_helper.go:356 (0x1ebe8b4)
        /source/services/actions/notifier_helper.go:233 (0x1ebd7ea)
        /source/services/actions/notifier_helper.go:112 (0x1ebc3fb)
        /source/services/actions/notifier.go:608 (0x1eba813)
        /source/services/notify/notify.go:325 (0x2567c2b)
        /source/services/mirror/mirror_pull.go:535 (0x25677fa)
        /source/services/mirror/mirror.go:27 (0x255eb49)
        /source/services/mirror/mirror.go:124 (0x255f4bd)
        /source/modules/queue/workerqueue.go:246 (0x1eee7e9)
        /source/modules/queue/workergroup.go:103 (0x1c77982)
        /source/modules/queue/workergroup.go:178 (0x1eecf44)
        /usr/local/go/src/runtime/asm_amd64.s:1695 (0x47b0a0)
                goexit: BYTE    $0x90   // NOP
```

**Comment by lunny** [comment]
Created https://gitea.com/go-chi/cache/pulls/17 and will upgrade Gitea's reference to resolve memcache problem.

**Comment by lunny** [comment]
Wait https://github.com/go-gitea/gitea/pull/32001
