### ISSUE TITLE
Action step with git authentication fails inside workflow_call when needs is set

### ISSUE THREAD

**Issue by javiertury** [go-gitea/gitea#31900]
### Description

Doing a git checkout (`actions/checkout@v4`) inside a `workflow_call` that `needs` another job raises an authentication error. 

It can be reproduced using the following nested workflow.

<details>
<summary>Workflow to reproduce the error</summary>

```yaml
# .gitea/workflows/main.yaml
name: test
run-name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      -
        name: Foo
        run: |
          echo 'foo: ${{ inputs.foo }}'

  # Works fine, even if it has a dependency
  outer_needy_checkout:
    runs-on: ubuntu-latest
    needs: [foo]
    steps:
      -
        name: Outer needy checkout
        uses: https://github.com/actions/checkout@v4

  nested_checkout:
    runs-on: ubuntu-latest
    uses: ./.gitea/workflows/nested-checkout.yaml
    with:
      foo: bar
    secrets: inherit

  nested_needy_checkout:
    runs-on: ubuntu-latest
    uses: ./.gitea/workflows/nested-checkout.yaml
    needs: [foo]
    with:
      foo: bar
    secrets: inherit
```

```yaml
# .git/workflows/nested-checkout.yaml

name: nested git checkout
run-name: nested git checkout
on:
  workflow_call:
    inputs:
      foo:
        type: string
        required: false

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      -
        name: Foo
        run: |
          echo 'foo: ${{ inputs.foo }}'
      # This checkout works fine too, even though we are in a workflow_call
      -
        name: Nested checkout
        uses: https://github.com/actions/checkout@v4

  # fatal: could not read Username for '<repo>': terminal prompts disabled
  inner_needy_checkout:
    runs-on: ubuntu-latest
    needs: [foo]
    steps:
      -
        name: Nested needy checkout
        uses: https://github.com/actions/checkout@v4
```
</details>

The step `Nested needy checkout` fails with

```
fatal: could not read Username for '<repo>': terminal prompts disabled
```

Bear in mind that due to bugs https://github.com/go-gitea/gitea/issues/26736 and https://github.com/go-gitea/gitea/issues/26187, the UI marks the job as a sucess, but reading the logs in details reveals the error.

### Gitea Version

1.22.1

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

![image](https://github.com/user-attachments/assets/cad8b4c8-5a9a-4de8-a716-eae025a74a28)

### How are you running Gitea?

I'm using the official gitea helm chart on k3s

### Database

SQLite

**Comment by Zettat123** [comment]
This bug is not related to `needs`. Actually, this bug can be reproduced without `needs`, but not stably. The reason should be that Gitea does not correctly handle reusable workflows with multiple jobs.

**Comment by lunny** [comment]
This should be fixed by https://gitea.com/gitea/act/pulls/116

**Comment by WereCatf** [comment]
> This should be fixed by https://gitea.com/gitea/act/pulls/116

Um, no, it's not. I just ran into this issue myself and authentication still fails with the "could not read Username for" message. Given that the issue is not fixed, I don't understand why this was closed.

**Comment by bircni** [comment]
Still an issue?
