### ISSUE TITLE
Feature request: option to default to private repository

### ISSUE THREAD

**Issue by mqudsi** [go-gitea/gitea#3235]
This is a minor feature request, yet somewhat important in that it pertains to security-related UX.

It would be nice to have either a per-user/organization or a global (site admin option) to default the checkbox controlling private repository status to a checked state. We had a few close calls with gitea where private code was almost checked into a public repository as a result of this, and would really appreciate such an option.

Keep in mind that something private can always be made public, but for a lot of private things once they are made public there's no ever taking them back.

Here's a screenshot to make it clear what option is being referred to:

![default checked](https://user-images.githubusercontent.com/606923/34175690-f2996276-e4c2-11e7-9053-abd1ff5e56c9.png)

(_I am not entirely sure, but I feel that gogs **may** have had such an option_)

**Comment by programmeroftheeve** [comment]
Set this in your app.ini config

```
[repository]
; Force every new repository to be private
FORCE_PRIVATE = false
```

This defaults new repos to private. They can always be changed to public afterwords.

**Comment by mqudsi** [comment]
Thanks. I've come across that but didn't realize that the user still had the option to make repositories public thereafter.

It would be nice to have a middle ground option where the checkmark can be ticked by default, but the user has the option of changing that at creation time.

**Comment by lafriks** [comment]
It is named badly but actually does exactly what you want, just makes private checked by default

**Comment by mqudsi** [comment]
@lafriks no, for me it forces the tick to be selected and that tick cannot be unselected on the new repo screen.

**Comment by mqudsi** [comment]
![image](https://user-images.githubusercontent.com/606923/34178337-75797272-e4cc-11e7-8dd4-8afa2debd4ab.png)

**Comment by lafriks** [comment]
Oh, sorry than. Quick look at code looked like it should not actually force but you are right

**Comment by mqudsi** [comment]
No problem. Thanks for the fast reply and changing the tag.

**Comment by strk** [comment]
I'd love to tweak that default-checked behavior too.
In my case I'd like new repositories to be public by default,
so unchecked-by-default.

And eventually an option to prevent some users from creating
private repositories at all...

**Comment by mqudsi** [comment]
Awesome! Thank you very much!

**Comment by robetus** [comment]
I understand that you can now make all new and migrated repos private default, but what about being about to remove the ability by users to make the repo private after it is created? This is what @mqudsi was asking about originally. Has this been implemented?

**Comment by mqudsi** [comment]
No, my issue has been addressed. You should probably open a new issue.

**Comment by chriseaton** [comment]
Why would a new issue be needed? This isn't actually resolved, shouldn't it be re-opened?

**Comment by chriseaton** [comment]
If you found this on Google, the option available is: `DEFAULT_PRIVATE = true`
