### ISSUE TITLE
Mobile Interface not align or overlay text

### ISSUE THREAD

**Issue by Sirherobrine23** [go-gitea/gitea#33107]
### Description

The interface is overlapped or does not appear at all, or is even below the texts, on screen landscape show normally 

### Screenshots

![Screenshot_20250105_083353_Chrome](https://github.com/user-attachments/assets/923a049f-0b93-4de6-8bbc-cc0ebd79b3a2)
![Screenshot_20250105_083336_Chrome](https://github.com/user-attachments/assets/f30185c5-7993-47b7-91ce-f77b2e205492)

![Screenshot_20250105_084134_Chrome](https://github.com/user-attachments/assets/92cdd24a-21b9-416b-b69b-ce22c320df85)
![Screenshot_20250105_084122_Chrome](https://github.com/user-attachments/assets/a344f545-e527-4647-be49-6f52d5decf02)

### Gitea Version

3078826d0111e818dc765d94c650f4cb5b3ecce7

### Can you reproduce the bug on the Gitea demo site?

Yes

### Operating System

Linux

### Browser Version

Chrome 131.0.6778.200 arm64

**Comment by wxiaoguang** [comment]
It has been fixed in 1.23-nightly and main branch.

**Comment by wxiaoguang** [comment]
Oops, there is another bug ........ will fix

**Comment by wxiaoguang** [comment]
Thank you very much for the report! I think these problems should have been fixed on main (by #33108) and 1.23-nightly (#33102) now.

Feel free to reopen if there are sill any problems.

**Comment by Sirherobrine23** [comment]
@wxiaoguang still not showing the list in the user's dropdown menu 

![Screenshot_20250105_210514_Chrome](https://github.com/user-attachments/assets/8190ad66-3e44-4faf-8fe7-2c74b77caefe)

**Comment by wxiaoguang** [comment]
> @wxiaoguang still not showing the list in the user's dropdown menu

Which version are you using?

**Comment by Sirherobrine23** [comment]
I use the main branch version, as soon as a commit comes out the server updates

**Comment by wxiaoguang** [comment]
I guess you are using an old version, because new versions here always use lower-case.

Yours:

![image](https://github.com/user-attachments/assets/e3219961-f2bc-4e0c-837a-f42f7e15ab62)

main/1.23-nightly:

![image](https://github.com/user-attachments/assets/b5f78298-112d-4a3c-8baa-5c1ef1e42c0e)

**Comment by Sirherobrine23** [comment]
My ci build log: https://sirherobrine23.com.br/Sirherobrine23/gitea_docker/actions/runs/30#jobstep-5-419

**Comment by Sirherobrine23** [comment]
@wxiaoguang in my computer is same text from my phone

https://github.com/user-attachments/assets/95b09b7c-98c8-49c5-a2ff-d82c0b3e59a5

**Comment by wxiaoguang** [comment]
> My ci build log: https://sirherobrine23.com.br/Sirherobrine23/gitea_docker/actions/runs/30#jobstep-5-419

I am not quite sure what happens in the CI, could you help to figure out more details? For example: could you pack the git commit id into your build to see which version the build is using? Or have you re-pulled the new image from your docker registry to deploy? And if the problem still exists, could you try to pull the gitea official image to check?


On my side, `image: gitea/gitea:1.23-nightly` and `image: gitea/gitea:nightly` both work fine:

![image](https://github.com/user-attachments/assets/bed35424-c559-45b4-b130-7fc78ec3a131)

![image](https://github.com/user-attachments/assets/2cba9fe5-4e88-4adc-a8f3-6986689002d4)

**Comment by Sirherobrine23** [comment]
show only "main" version

![image](https://github.com/user-attachments/assets/be1725ea-7981-4050-bf3a-94da6d847376)

**Comment by wxiaoguang** [comment]
> show only "main" version

You need to set it during the build/CI, see how Gitea's makefile does.

And:

* Or have you re-pulled the new image from your docker registry to deploy?
* And if the problem still exists, could you try to pull the gitea official image to check?

It seems related to your build.

**Comment by Sirherobrine23** [comment]
I will build the local docker image on my machine and test it locally, if it is a problem in my build I will take a look to see if it was not my error, and i pull latest build from registry

**Comment by Sirherobrine23** [comment]
Sorry, I will be reviewing my registry image, the official image worked fine here
