### ISSUE TITLE
Link to Existing Account - Only option is Passkey

### ISSUE THREAD

**Issue by hanley-development** [go-gitea/gitea#33437]
### Description

Unable to link to existing account using authentik - openid/oauth2 using basic username and password. When attempting to link the only option it gives is passkey. Login form is either broken or there is a setting unknown to allow linking account via username and password.  Registering new account works and allows the ability to then set password to login via authentik or username and password.

### Gitea Version

1.23.1

### Can you reproduce the bug on the Gitea demo site?

No

### Git Version

2.47.1

### Operating System

Ubuntu 24.04

### How are you running Gitea?

Docker

### Database

MySQL/MariaDB

**Comment by wxiaoguang** [comment]
It should have been fixed in 1.23-nightly (which contains many necessary bug fixes, it is a stable release and will be 1.23 soon)

* https://dl.gitea.com/gitea/1.23-nightly/
* https://hub.docker.com/r/gitea/gitea/tags?name=1.23-nightly

**Comment by lautriva** [comment]
One of my users reported the problem still exists on 1.23.6 (maybe a regression?)

![Image](https://github.com/user-attachments/assets/4504b5c1-49bd-4c59-9ecc-31d41358f943)

**Comment by wxiaoguang** [comment]
Maybe not a regression but not fully fixed?

**Comment by j0nv0** [comment]
My users consistently have this issue 1.23.6, regardless of #33437 being closed.

**Comment by valentimarco** [comment]
same issue in gitea:latest docker image using Authelia as idp.

**Comment by wxiaoguang** [comment]
I am not working on it. If you have some clues about how to fix, feel free to propose a change. Thank you very much.

**Comment by Salvora** [comment]
I have come across this issue in a different form as well. But when ACCOUNT_LINKING is set to login, it shows only the username password fields.
However, the Oauth auto registered users dont have passwords and only use oauth to login.
In this case, I cannot link accounts from different Idps. If a user is auto registered via Entra with no password and uses only Entra as login, how to link the account? We need to be able to have the different oauth sources in the account linking page as well to link accounts between different idps.
