### ISSUE TITLE
"run-name:" not working within action to define the name of the run

### ISSUE THREAD

**Issue by laitco** [go-gitea/gitea#34247]
### Description

Hi!

i dont now if it is a bug or Layer7. I cannot get it working to define a fixed run name like it is done within the blog "https://blog.gitea.com/hacking-on-gitea-actions/".

name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]
jobs:

When i am adding run-name it is still showing the commit message.

Am i doing something wrong or can someone help?

Not reproducable in demo, because CI/CD.

### Gitea Version

1.23.7

### Can you reproduce the bug on the Gitea demo site?

No

### Operating System

Linux

### How are you running Gitea?

Docker

### Database

SQLite

**Comment by lunny** [comment]
Can you reproduce it in https://demo.gitea.com ?

**Comment by laitco** [comment]
Hi @lunny!

Yes. 

Test-Repo:
https://demo.gitea.com/laitco/run-name-issue

Screens:

![Image](https://github.com/user-attachments/assets/61abd162-a9e4-44de-9dc5-0ac86fdcb3bb)

![Image](https://github.com/user-attachments/assets/66b99b17-b929-4299-bf3e-77670cbbf39a)

![Image](https://github.com/user-attachments/assets/793afa67-8dd8-4456-ae23-4d5a996b9be1)

**Comment by badhezi** [comment]
From what I personally remember this used to work but for the life of me i can't get it to work locally.
I also don't see how this will ever work the way we currently handle the creation of an cation job run.

https://github.com/go-gitea/gitea/blob/0376c09fc27d848dbac471b629c83fd7a231852b/services/actions/notifier_helper.go#L303

@lunny / @Zettat123 I can take the implementation of this if this actually needs implementing.

To my understanding we need to modify [this part of act code](https://github.com/go-gitea/gitea/blob/0376c09fc27d848dbac471b629c83fd7a231852b/services/actions/notifier_helper.go#L303) to include run-name

Also do we go about expanding `${{ gitea.* }}` variables in server?

thanks.

**Comment by badhezi** [comment]
Created a preliminary PR for this, would love to get feedback
https://github.com/go-gitea/gitea/pull/34301

**Comment by badhezi** [comment]
I believe this can be resolved soon, waiting for review on
https://gitea.com/gitea/act/pulls/136
and https://github.com/go-gitea/gitea/pull/34301
@lunny

**Comment by laitco** [comment]
Is it fixed in the newest version because it was merged into main?

**Comment by badhezi** [comment]
@laitco no this is not fixed yet, the PR in  this repo still needs to me merged, it's ready however. Waiting for review and feedback.

**Comment by wxiaoguang** [comment]
Fixed by  Use run-name and evaluate workflow variables #34301  and can be closed?

**Comment by laitco** [comment]
Can be closed. Will test when i will be released in stable.
