### ISSUE TITLE
Disabling /api and /api/swagger endpoints

### ISSUE THREAD

**Issue by 0rzech** [go-gitea/gitea#3498]
It would be nice, if there were options to disable /api and /api/swagger endpoints.

**Comment by lafriks** [comment]
What is use case for disabling API?

**Comment by 0rzech** [comment]
When one doesn't want to expose it at all, eg. to reduce attack surface.

**Comment by lafriks** [comment]
You can use nginx in front of gitea and than disable everything starting with `/api`

**Comment by 0rzech** [comment]
Yes, but the link to [API](https://try.gitea.io/api/swagger) will remain in footer.

**Comment by lafriks** [comment]
It will not work anyway ;) not the best option but you can change template if that is really needed

**Comment by 0rzech** [comment]
Yes, but IMHO it's a bit too dirty to change template and server configuration to achieve that.

**Comment by lafriks** [comment]
Of course option to hide swagger link can be added

**Comment by 0rzech** [comment]
Cool. Thanks for your input.

**Comment by lunny** [comment]
resolved by #3502

**Comment by shuhaowu** [comment]
The other PR doesn't actually disable /api, right? Only /api/swagger (which is the documentation endpoint and try it out interface??) is disabled in that PR afaict.

Thus this is not quite resolved with that option. To work around this, you can disable access to /api in the reverse proxy setup link nginx on the node. The /api/internal endpoints should stay unaffected with this because gitea by default tries to build the internal API calls' urls via HTTP_ADDR:HTTP_PORT specified in the settings, which doesn't go through the reverse proxy locally. Just ensure that you only bind with HTTP_ADDR = 127.0.0.1.

**Comment by lafriks** [comment]
@shuhaowu not true, gitea also uses API for some functionality so it can not be disabled fully without loosing some functionality

**Comment by 0rzech** [comment]
@shuhaowu Gitea front-end uses API as well. You can find it [here](https://github.com/go-gitea/gitea/search?q=%2Fapi%2Fv1+path%3Apublic%2Fjs).

**Comment by 0rzech** [comment]
@shuhaowu Gitea front-end uses API as well. You can find it [here](/go-gitea/gitea/blob/344dc07239301194fa4220a27ce4dd24396cf25c/public/js/index.js). Just look for `/api` occurrences.

**Comment by gerroon** [comment]
> What is use case for disabling API?

I just realized that non users can get user names without signed in, I do not know how this is not a security issue.

**Comment by techknowlogick** [comment]
@gerroon you can get the same information from the webapp itself example: https://try.gitea.io/explore/users

This ticket is closed, if you have a feature request please create a new issue, however disabling the API is not possible as mentioned above the web interface makes use of it.
