### ISSUE TITLE
[E] PANIC: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by superkraft-io** [go-gitea/gitea#35148]
### Description

I encounter the error "[E] PANIC: runtime error: invalid memory address or nil pointer dereference" when I push a mirror of my BitBucket repo.

Here are the steps to reproduce:

```
git clone --mirror https://bitbucket.org/username/repo.git
cd njoy_ups_monitor.git
git remote set-url origin http://192.168.1.14:3000/username/repo.git
git push --mirror
```

Here is my log
```Jul 23 11:45:41 splitter-git gitea[1761]: 2025/07/23 11:45:41 HTTPRequest [I] router: completed GET /repo/search?sort=updated&order=desc&uid=1&team_id=undefined&q=&page=1&limit=15&mode=&archived=false for 192.168.1.3:55046, 200 OK in 4.4ms @ repo/repo.go:459(repo.SearchRepo)
Jul 23 11:45:42 splitter-git gitea[1761]: 2025/07/23 11:45:42 HTTPRequest [I] router: completed GET /aid/njoy_ups_monitor/commit/f0c6615d00bfe4a8b5c377155cae427bdb57eb2d for 192.168.1.3:55046, 200 OK in 166.0ms @ repo/commit.go:278(repo.Diff)
Jul 23 11:45:42 splitter-git gitea[1761]: 2025/07/23 11:45:42 HTTPRequest [I] router: completed GET /avatars/9ee0d07fbe275c9cbafaa7de38aabefe?size=40 for 192.168.1.3:55049, 200 OK in 4.9ms @ web/base.go:22(avatars)
Jul 23 11:45:45 splitter-git gitea[1761]: 2025/07/23 11:45:45 HTTPRequest [I] router: polling   GET /user/events for 192.168.1.3:55046, elapsed 3037.8ms @ events/events.go:18(events.Events)
Jul 23 11:45:46 splitter-git gitea[1761]: 2025/07/23 11:45:46 HTTPRequest [I] router: completed GET /aid/njoy_ups_monitor/settings for 192.168.1.3:55049, 200 OK in 38.1ms @ setting/setting.go:94(setting.Settings)
Jul 23 11:45:49 splitter-git gitea[1761]: 2025/07/23 11:45:49 HTTPRequest [I] router: polling   GET /user/events for 192.168.1.3:55049, elapsed 3377.8ms @ events/events.go:18(events.Events)
Jul 23 11:45:55 splitter-git gitea[1761]: 2025/07/23 11:45:55 services/actions/cleanup.go:164:CleanupEphemeralRunnersByPickedTaskOfRepo() [I] Removed 0 runners
Jul 23 11:45:55 splitter-git gitea[1761]: 2025/07/23 11:45:55 HTTPRequest [I] router: completed POST /aid/njoy_ups_monitor/settings for 192.168.1.3:55050, 303 See Other in 215.4ms @ setting/setting.go:99(setting.SettingsPost)
Jul 23 11:45:55 splitter-git gitea[1761]: 2025/07/23 11:45:55 HTTPRequest [I] router: completed GET / for 192.168.1.3:55050, 200 OK in 5.8ms @ web/home.go:32(web.Home)
Jul 23 11:45:55 splitter-git gitea[1761]: 2025/07/23 11:45:55 HTTPRequest [I] router: completed GET /repo/search?count_only=1&uid=1&team_id=undefined&q=&page=1&mode= for 192.168.1.3:55050, 200 OK in 1.7ms @ repo/repo.go:459(repo.SearchRepo)
Jul 23 11:45:55 splitter-git gitea[1761]: 2025/07/23 11:45:55 HTTPRequest [I] router: completed GET /repo/search?sort=updated&order=desc&uid=1&team_id=undefined&q=&page=1&limit=15&mode=&archived=false for 192.168.1.3:55051, 200 OK in 3.7ms @ repo/repo.go:459(repo.SearchRepo)
Jul 23 11:45:57 splitter-git gitea[1761]: 2025/07/23 11:45:57 HTTPRequest [I] router: completed POST /user/logout for 192.168.1.3:55051, 200 OK in 1.3ms @ auth/auth.go:410(auth.SignOut)
Jul 23 11:45:57 splitter-git gitea[1761]: 2025/07/23 11:45:57 HTTPRequest [I] router: completed POST /-/fetch-redirect for 192.168.1.3:55051, 303 See Other in 0.1ms @ common/redirect.go:13(common.FetchRedirectDelegate)
Jul 23 11:45:57 splitter-git gitea[1761]: 2025/07/23 11:45:57 HTTPRequest [I] router: completed GET / for 192.168.1.3:55051, 200 OK in 3.2ms @ web/home.go:32(web.Home)
Jul 23 11:45:58 splitter-git gitea[1761]: 2025/07/23 11:45:58 HTTPRequest [I] router: completed GET /user/login?redirect_to=%2f for 192.168.1.3:55051, 200 OK in 7.6ms @ auth/auth.go:184(auth.SignIn)
Jul 23 11:46:01 splitter-git gitea[1761]: 2025/07/23 11:46:01 HTTPRequest [I] router: completed POST /user/login for 192.168.1.3:55051, 303 See Other in 60.8ms @ auth/auth.go:197(auth.SignInPost)
Jul 23 11:46:01 splitter-git gitea[1761]: 2025/07/23 11:46:01 HTTPRequest [I] router: completed GET / for 192.168.1.3:55051, 200 OK in 6.7ms @ web/home.go:32(web.Home)
Jul 23 11:46:01 splitter-git gitea[1761]: 2025/07/23 11:46:01 HTTPRequest [I] router: completed GET /avatars/0e94dc74cd8eca66bbcb9906322136b3?size=48 for 192.168.1.3:55051, 200 OK in 0.9ms @ web/base.go:22(avatars)
Jul 23 11:46:01 splitter-git gitea[1761]: 2025/07/23 11:46:01 HTTPRequest [I] router: completed GET /repo/search?count_only=1&uid=2&team_id=undefined&q=&page=1&mode= for 192.168.1.3:55051, 200 OK in 2.2ms @ repo/repo.go:459(repo.SearchRepo)
Jul 23 11:46:01 splitter-git gitea[1761]: 2025/07/23 11:46:01 HTTPRequest [I] router: completed GET /repo/search?sort=updated&order=desc&uid=2&team_id=undefined&q=&page=1&limit=15&mode=&archived=false for 192.168.1.3:55051, 200 OK in 3.1ms @ repo/repo.go:459(repo.SearchRepo)
Jul 23 11:46:04 splitter-git gitea[1761]: 2025/07/23 11:46:04 HTTPRequest [I] router: completed GET /repo/create for 192.168.1.3:55052, 200 OK in 7.2ms @ repo/repo.go:160(repo.Create)
Jul 23 11:46:07 splitter-git gitea[1761]: 2025/07/23 11:46:07 HTTPRequest [I] router: completed POST /repo/create for 192.168.1.3:55064, 303 See Other in 284.8ms @ repo/repo.go:218(repo.CreatePost)
Jul 23 11:46:07 splitter-git gitea[1761]: 2025/07/23 11:46:07 HTTPRequest [I] router: completed GET /aid/njoy_ups_monitor for 192.168.1.3:55064, 200 OK in 15.5ms @ repo/view_home.go:390(repo.Home)
Jul 23 11:46:11 splitter-git gitea[1761]: 2025/07/23 11:46:11 HTTPRequest [I] router: polling   GET /user/events for 192.168.1.3:55064, elapsed 3809.1ms @ events/events.go:18(events.Events)
Jul 23 11:46:32 splitter-git gitea[1761]: 2025/07/23 11:46:32 HTTPRequest [I] router: completed GET /aid/njoy_ups_monitor/issues for 192.168.1.3:55065, 200 OK in 21.7ms @ repo/issue_list.go:761(repo.Issues)
Jul 23 11:46:33 splitter-git gitea[1761]: 2025/07/23 11:46:33 HTTPRequest [I] router: completed GET /aid/njoy_ups_monitor/src/ for 192.168.1.3:55067, 303 See Other in 4.8ms @ web/web.go:1600(web.registerWebRoutes.func54.(*Router).Group.registerWebRoutes.func54.10.14)
Jul 23 11:46:33 splitter-git gitea[1761]: 2025/07/23 11:46:33 HTTPRequest [I] router: completed GET /aid/njoy_ups_monitor for 192.168.1.3:55067, 200 OK in 39.5ms @ repo/view_home.go:390(repo.Home)
Jul 23 11:46:36 splitter-git gitea[1761]: 2025/07/23 11:46:36 HTTPRequest [I] router: polling   GET /user/events for 192.168.1.3:55067, elapsed 3402.4ms @ events/events.go:18(events.Events)
Jul 23 11:46:55 splitter-git gitea[1761]: 2025/07/23 11:46:55 HTTPRequest [I] router: completed GET /aid/njoy_ups_monitor.git/info/refs?service=git-receive-pack for 192.168.1.3:55069, 401 Unauthorized in 1.3ms @ repo/githttp.go:511(repo.GetInfoRefs)
Jul 23 11:46:56 splitter-git gitea[1761]: 2025/07/23 11:46:56 HTTPRequest [I] router: completed GET /aid/njoy_ups_monitor.git/info/refs?service=git-receive-pack for 192.168.1.3:55069, 200 OK in 30.0ms @ repo/githttp.go:511(repo.GetInfoRefs)
Jul 23 11:46:56 splitter-git gitea[1761]: 2025/07/23 11:46:56 HTTPRequest [I] router: completed POST /api/internal/hook/pre-receive/aid/njoy_ups_monitor for 127.0.0.1:0, 200 OK in 2.4ms @ private/hook_pre_receive.go:106(private.HookPreReceive)
Jul 23 11:46:56 splitter-git gitea[1761]: 2025/07/23 11:46:56 HTTPRequest [I] router: completed POST /api/internal/hook/post-receive/aid/njoy_ups_monitor for 127.0.0.1:0, 200 OK in 34.9ms @ private/hook_post_receive.go:33(private.HookPostReceive)
Jul 23 11:46:56 splitter-git gitea[1761]: 2025/07/23 11:46:56 HTTPRequest [I] router: completed POST /api/internal/hook/set-default-branch/aid/njoy_ups_monitor/master for 127.0.0.1:0, 200 OK in 20.5ms @ private/default_branch.go:18(private.SetDefaultBranch)
Jul 23 11:46:56 splitter-git gitea[1761]: 2025/07/23 11:46:56 HTTPRequest [I] router: completed POST /aid/njoy_ups_monitor.git/git-receive-pack for 192.168.1.3:55069, 200 OK in 473.9ms @ repo/githttp.go:479(repo.ServiceReceivePack)
Jul 23 11:46:59 splitter-git gitea[1761]: 2025/07/23 11:46:59 HTTPRequest [I] router: completed GET /aid/njoy_ups_monitor/issues for 192.168.1.3:55068, 200 OK in 53.9ms @ repo/issue_list.go:761(repo.Issues)
Jul 23 11:47:00 splitter-git gitea[1761]: 2025/07/23 11:47:00 HTTPRequest [I] router: completed GET /aid/njoy_ups_monitor/src/ for 192.168.1.3:55070, 303 See Other in 19.9ms @ web/web.go:1600(web.registerWebRoutes.func54.(*Router).Group.registerWebRoutes.func54.10.14)
Jul 23 11:47:00 splitter-git gitea[1761]: 2025/07/23 11:47:00 HTTPRequest [W] router: failed    GET /aid/njoy_ups_monitor for 192.168.1.3:55070, panic in 43.8ms @ repo/view_home.go:390(repo.Home), err=runtime error: invalid memory address or nil pointer dereference
Jul 23 11:47:00 splitter-git gitea[1761]: 2025/07/23 11:47:00 routers/common/errpage.go:25:RenderPanicErrorPage() [E] PANIC: runtime error: invalid memory address or nil pointer dereference
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/runtime/panic.go:792 (0x47b9f1)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/modules/web/routing/logger_manager.go:116 (0x18025c4)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/runtime/panic.go:792 (0x47b9f1)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/runtime/panic.go:262 (0x47e0d8)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/runtime/signal_unix.go:925 (0x47e0a8)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/modules/git/commit_info.go:21 (0xe918e3)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/modules/git/commit_info_nogogit.go:70 (0xe91ef2)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/routers/web/repo/view.go:302 (0x2a21104)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/routers/web/repo/view_home.go:136 (0x2a26d0b)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/routers/web/repo/view_home.go:340 (0x2a291cd)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/routers/web/repo/view_home.go:469 (0x2a28b61)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/reflect/value.go:584 (0x50a4e5)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/reflect/value.go:368 (0x5095f8)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/modules/web/handler.go:161 (0x180bed6)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/modules/web/handler.go:168 (0x180bf45)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/modules/web/handler.go:168 (0x180bf45)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/modules/web/handler.go:168 (0x180bf45)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/modules/web/handler.go:168 (0x180bf45)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.2/chain.go:31 (0x1802ea5)
Jul 23 11:47:00 splitter-git gitea[1761]: /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.2/mux.go:478 (0x1806041)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/modules/web/handler.go:168 (0x180bf45)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/modules/web/handler.go:168 (0x180bf45)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.2/middleware/get_head.go:37 (0x296e46a)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/modules/web/handler.go:125 (0x180c395)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/modules/web/handler.go:168 (0x180bf45)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/services/context/context.go:209 (0x1e06658)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/modules/web/handler.go:125 (0x180c395)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /go/pkg/mod/gitea.com/go-chi/session@v0.0.0-20240316035857-16768d98ec96/session.go:257 (0x17aba6d)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/modules/web/handler.go:125 (0x180c395)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.2/mux.go:73 (0x1803aee)
Jul 23 11:47:00 splitter-git gitea[1761]: /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.2/mux.go:325 (0x180545a)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.2/mux.go:478 (0x1806041)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.2/mux.go:73 (0x1803aee)
Jul 23 11:47:00 splitter-git gitea[1761]: /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.2/mux.go:325 (0x180545a)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.2/mux.go:478 (0x1806041)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/modules/web/routing/logger_manager.go:122 (0x180244e)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/modules/web/handler.go:125 (0x180c395)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /go/pkg/mod/github.com/chi-middleware/proxy@v1.1.1/middleware.go:37 (0x28b7213)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/modules/web/handler.go:125 (0x180c395)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/routers/common/middleware.go:78 (0x28b94fc)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/modules/web/handler.go:125 (0x180c395)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/routers/common/middleware.go:93 (0x28b9072)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/modules/web/handler.go:125 (0x180c395)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2294 (0x910948)
Jul 23 11:47:00 splitter-git gitea[1761]: /go/pkg/mod/github.com/go-chi/chi/v5@v5.2.2/mux.go:90 (0x1803aad)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/modules/web/router.go:243 (0x180de5b)
Jul 23 11:47:00 splitter-git gitea[1761]: /source/modules/web/router.go:181 (0x180d886)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:3301 (0x93140d)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/net/http/server.go:2102 (0x90ee44)
Jul 23 11:47:00 splitter-git gitea[1761]: /usr/local/go/src/runtime/asm_amd64.s:1700 (0x484060)```

### Gitea Version

1.24.3

### Can you reproduce the bug on the Gitea demo site?

No

### Log Gist

_No response_

### Screenshots

_No response_

### Git Version

_No response_

### Operating System

_No response_

### How are you running Gitea?

Locally in a KVM/QEMU VM on Ubuntu

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
It should have been fixed in 1.24 nightly (it will be 1.24.4 soon)

* https://dl.gitea.com/gitea/1.24-nightly/
* https://hub.docker.com/r/gitea/gitea/tags?name=1.24-nightly

The root cause is that there is an invalid submodule (no entry in `.gitmodules`) in the repo.

**Comment by superkraft-io** [comment]
I see, well, it’s still happening.

Here is some more info:

- My repo does not have a .submodules file
- Comitting, pushing, pulling and cloning the gitea repo from a git client like GitHub Desktop seems to work fine
- The error seems to be web server related, not necessarily Gitea git related. In a sense UI related.


Maybe how to reproduce more avcurately(?):

- Create a repo called A
- Clone a different repo (B) as a submodule into A
- Repo A now has repo B
- Ensure that A does not have a .submodules file
- Push to gitea server

**Comment by wxiaoguang** [comment]
> ### Gitea Version
> 
> 1.24.3

Have you tried upgrading your Gitea to 1.24 nightly?

**Comment by superkraft-io** [comment]
> > ### Gitea Version
> > 1.24.3
> 
> Have you tried upgrading your Gitea to 1.24 nightly?

I have not. How do I upgrade to 1.14 nightly?

**Comment by wxiaoguang** [comment]
See this:  https://github.com/go-gitea/gitea/issues/35148#issuecomment-3106891516

* https://dl.gitea.com/gitea/1.24-nightly/
* https://hub.docker.com/r/gitea/gitea/tags?name=1.24-nightly

**Comment by superkraft-io** [comment]
The nightly build fixed this issue.

**Comment by wxiaoguang** [comment]
> It should have been fixed in 1.24 nightly (it will be 1.24.4 soon)

Yup, it should 😄
