### ISSUE TITLE
Cannot make steps run sequentially with matrix and max-parallel = 1

### ISSUE THREAD

**Issue by kenho811** [go-gitea/gitea#35561]
### Description

Using gitea 1.24.6, I have the below workflow file.

```
name: Scheduled Assets Journal

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false 
      matrix:
        config:
          - { stock_code: '00291', market: 'HK', investingdotcom_index_symbols: '[]' }
          - { stock_code: '09922', market: 'HK', investingdotcom_index_symbols: '[]' }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Run Single Assets Journal Action
        uses: ./.gitea/actions/run_single_assets_journal
        with:
          stock_code: ${{ matrix.config.stock_code }}
          market: ${{ matrix.config.market }}
          investingdotcom_index_symbols: ${{ matrix.config.investingdotcom_index_symbols }}
```

I want the the steps to run sequentially while using matrix syntax.

However, they are running in parallel. So it looks like that the `trigger.strategy.max-parallel` configuration is not working.

<img width="1771" height="908" alt="Image" src="https://github.com/user-attachments/assets/b026831a-ce94-4b9d-8215-eac0db41e576" />

Reference: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#jobsjob_idstrategymax-parallel

### Gitea Version

1.24.6

### Can you reproduce the bug on the Gitea demo site?

Yes

### How are you running Gitea?

I am self-hosting gitea with act-runner

### Database

PostgreSQL

**Comment by kenho811** [comment]
Hi,

Any insight?

**Comment by ChristopherHX** [comment]
I do not think max-parallel is implemented right now

Gitea Actions currently duplicates the jobs when triggering the workflow, then they are all queued in parallel.

There are more things not (correctly) implemented.

**Comment by ZPascal** [comment]
**FYI:** @ChristopherHX I've implemented it [here](https://gitea.com/gitea/act/pulls/150) and [here](https://github.com/go-gitea/gitea/pull/36357).

**Comment by kenho811** [comment]
Thanks so much @ZPascal .

That would be great

**Comment by TheFox0x7** [comment]
This doesn't resolve the issue though. The linked PR claims to (I have not vetted it, I just looked at it enough to know it's not relevant here) limit the concurrent execution of jobs to the max-parallel setting when using act directly, which isn't the case here as it the runner instance gets only one job.

**Comment by huoxingdawang** [comment]
I am using 1.25.3 and it has the same issue.

**Comment by uvulpos** [comment]
The issue also affects more features of github action, e.g. the use of `uses` and `needs` to import jobs also results in a task that never gets assigned

**Comment by ZPascal** [comment]
> The issue also affects more features of github action, e.g. the use of `uses` and `needs` to import jobs also results in a task that never gets assigned

@uvulpos, I would like to check whether this is covered by my pull request. Could you please explain this to me in detail?

**Comment by uvulpos** [comment]
@ZPascal did not check your pr's in detail yet, but to me there is also an UI missing. To my understanding such an interface does not exist yet on gitea. My point is, it is not possible to import different jobs from other files. To do this there is also an parallel execution nessesary

<img width="1008" height="796" alt="Image" src="https://github.com/user-attachments/assets/ab75d61a-a319-482b-893c-684b24b60e17" />

**Comment by uvulpos** [comment]
for the given example not nessesarly needed, but pipelines like that run parallel:
<img width="1574" height="248" alt="Image" src="https://github.com/user-attachments/assets/3140369e-6ee3-41ba-94f5-595d813a3219" />

**Comment by ZPascal** [comment]
@uvulpos do you mean the [reuse workflow functionality ](https://docs.github.com/en/actions/how-tos/reuse-automations/reuse-workflows) from GitHub?

**Comment by uvulpos** [comment]
ah yes, thats the official name apperantly

**Comment by ZPascal** [comment]
@uvulpos That is not supported by the PR, and I think the feature request should be tracked in a separate issue.

**Comment by huoxingdawang** [comment]
Hi, 
Any progress? Still having the problem in v1.26.1 .

**Comment by bircni** [comment]
there is already a PR for reuse

**Comment by bircni** [comment]
reusable workflows were implemented here: https://github.com/go-gitea/gitea/pull/37478

**Comment by ghnp5** [comment]
Experiencing the same issue in v1.26.4, with gitea-runner v2.0.0.
`max-parallel: 1` ran all the jobs in parallel.

@bircni - what does "reusable workflows" have to do with this? #37478 seems completely unrelated to the issue being reported here.

I think this Issue should be re-opened.

**Comment by ghnp5** [comment]
`max-parallel` might not be working because #36357 hasn't been merged yet.
