### ISSUE TITLE
No Email notifications

### ISSUE THREAD

**Issue by top-psi** [go-gitea/gitea#35657]
### Description

We do not receive E-Mail notifications for certain projects.

What I can do is sending E-Mail notifications via admin - config - sending testing email
I receive notifications in the bell icon.

I also have a Gitea Server for testing and newly created organisations / projects do not send notifications either.

However, I used to receive emails from "older" Projects that we migrated at the beginning of using gitea. At some point we disabled AUTO_WATCH_NEW_REPOS to make the people opt in for notifications.
(my test installation has this not disabled tho)

Now comes the weird thing, while testing today I unfollowed and followed an organisation where I got emails from and now I do not receive any email notifications at all. Even from the projects that are not in that particular organisation I unfollowed / followed.

Relevant configuration options:
AUTO_WATCH_NEW_REPOS = false
ENABLE_NOTIFY_MAIL = true

[mailer]
ENABLED        = true
FROM           = REDACTED
PROTOCOL       = smtp+starttls
SMTP_ADDR      = REDACTED
SMTP_PORT      = 25

### Gitea Version

1.24.6

### Can you reproduce the bug on the Gitea demo site?

No

### Screenshots

<img width="1313" height="1171" alt="Image" src="https://github.com/user-attachments/assets/b15ec0d3-2ad9-41ae-900c-720b22473216" />

<img width="1362" height="72" alt="Image" src="https://github.com/user-attachments/assets/81d058c7-238e-4c99-9756-96df7a475249" />

### Operating System

RHEL9

### How are you running Gitea?

Docker

### Database

PostgreSQL

**Comment by wxiaoguang** [comment]
Goto admin panel, to see whether the email queue is stuck

<img width="2476" height="1254" alt="Image" src="https://github.com/user-attachments/assets/cf2a0f3a-f8e1-4d02-93e0-cad2c343ef78" />

**Comment by andrea-maruccia-n** [comment]
Similar behavior here, no emails in the queue. When is Gitea supposed to send an email? The only emails that I ever got from Gitea is the admin test email and the recover password email.

When I mention an user (or myself) I don't get an email, and no email is in the queue. Are there some logs we can verify when an email is supposed to be sent?

**Comment by lunny** [comment]
This should be fixed by #35816

**Comment by top-psi** [comment]
Still not fixed. I am running 1.25.1, when creating new projects they do not send notifications even when followed / watched / stared. There are "older" projects that do. The project that does was imported with gitea version 1.23.4 (pretty sure :D) @lunny

**Comment by lunny** [comment]
The port seems not right, it should 587 by default for `smtp+starttls`.

```diff
 [mailer]
 ENABLED = true
 FROM = REDACTED
 PROTOCOL = smtp+starttls
 SMTP_ADDR = REDACTED
-SMTP_PORT = 25
+SMTP_PORT = 587
```

**Comment by lunny** [comment]
I have tested #36055 locally, it works for gmail.
