### ISSUE TITLE
Mail Error: double encapsulation of receipient in "angle-brackets".

### ISSUE THREAD

**Issue by migmedia** [go-gitea/gitea#35948]
### Description

Error-message in admin-config `/-/admin/config` after testing email-notification:  `Das Senden der Test-E-Mail an 'email@example.com' ist fehlgeschlagen: exit status 70`

### mail.log-file: 
```
Nov 13 13:06:38 repos smtpd[15803]: 40be12f790a003e1 smtp failed-command command="RCPT TO:<<email@example.com>> " result="501 5.1.3 Recipient address syntax error"
```
The double encapsulation of the recipient in "angle-brackets" is not correct: `<<` recipient_address `>>`

### gitea-config:
```ini
[mailer]
ENABLED = true
;; Prefix displayed before subject in mail
SUBJECT_PREFIX = [Gitea]
;; Mail server
;; Gmail: smtp.gmail.com:587
;; QQ: smtp.qq.com:465
;; As per RFC 8314 using Implicit TLS/SMTPS on port 465 (if supported) is recommended,
;; otherwise STARTTLS on port 587 should be used.
PROTOCOL      = sendmail
SENDMAIL_PATH = /usr/sbin/sendmail
; most "sendmail" programs take options, "--" will prevent an email address being interpreted as an option.
SENDMAIL_ARGS = "--" 
; Mail from address, RFC 5322. This can be just an email address, or the `"Name" <email@example.com>` format
FROM = "Gitea" <gitea@example.com>
; Send mails as plain text
SEND_AS_PLAIN_TEXT = false
```

Maybe a regression alike /pull/35833? The (smtp)-mail-lib changed their Address handling but I use the sendmail-function.

### Gitea Version

1.25.1

### Can you reproduce the bug on the Gitea demo site?

No

### How are you running Gitea?

Compiled from source https://github.com/go-gitea/gitea/releases/download/1.25.1/gitea-src-1.25.1.tar.gz compiled. (gentoo ebuild)

### Database

None

**Comment by lunny** [comment]
But the only change line of #35833 is in the file `services/mailer/sender/smtp.go` which should not affect `services/mailer/sender/sendmail.go`.

**Comment by wxiaoguang** [comment]
> But the only change line of [#35833](https://github.com/go-gitea/gitea/pull/35833) is in the file `services/mailer/sender/smtp.go` which should not affect `services/mailer/sender/sendmail.go`.

It is a regression bug from "upgrade go mail to 0.7.2 and fix the bug #35833", read the code again.

**Comment by wxiaoguang** [comment]
By the way, as a workaround, maybe you can set `ENVELOPE_FROM` in app.ini then bypass the bug.

**Comment by migmedia** [comment]
> By the way, as a workaround, maybe you can set `ENVELOPE_FROM` in app.ini then bypass the bug.

The problem is the `To:` / `Rcpt To`-address. Changing the sender-address doesn't help. So my assumption of a correlation to the change in the [`go-mail`](/wneessen/go-mail)-lib may be misleading.

**Comment by wxiaoguang** [comment]
> > By the way, as a workaround, maybe you can set `ENVELOPE_FROM` in app.ini then bypass the bug.
> 
> The problem is the `To:` / `Rcpt To`-address. Changing the sender-address doesn't help. So my assumption of a correlation to the change in the [`go-mail`](/wneessen/go-mail)-lib may be misleading.

The sendmail "sender" also uses the data from "go-mail" package. 

<details>

<img width="1446" height="144" alt="Image" src="https://github.com/user-attachments/assets/a671a26e-99eb-45c4-b7b8-f387ace463e3" />

<img width="1660" height="812" alt="Image" src="https://github.com/user-attachments/assets/ba840e24-a12c-4eb2-b82d-4f543c8b4d30" />

</details>

**Comment by wxiaoguang** [comment]
By the way, AI said : `sendmail "<email@domain.com>"` is valid, but I am not sure and I have no idea how the regression occurs (sorry, I don't use sendmail). The almost certain thing is that the go-mail package's changed behavior causes the problem, and Gitea's code is not quite right either.


@lunny  will you fix it?

<details>

<img width="1662" height="1458" alt="Image" src="https://github.com/user-attachments/assets/8d059812-4861-45f8-a962-56824b640612" />

</details>

**Comment by lunny** [comment]
I’ll start working on a fix for this issue.

**Comment by lunny** [comment]
This should be resolved by #36055

**Comment by migmedia** [comment]
Thanks @lunny. I have applied your patch at my gitea-1.25.1 installation.
Unfortunately the error persists.

**Comment by lunny** [comment]
@migmedia Thank you for the feedback. I found the problem. I just changed smtp sender and forgot sendmail. e708b564a0 should fix that. Please help to try again.

**Comment by migmedia** [comment]
I can confirm, that patch fixed my problem. Thank you!
