### ISSUE TITLE
Non-empty repository is shown as empty

### ISSUE THREAD

**Issue by Sudiukil** [go-gitea/gitea#4134]
## Informations

- Gitea version (or commit ref): 1.4.1 (binary release)
- Git version: 2.1.4
- Operating system: Debian 8 x64
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gitea.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant (different Gitea version)
- Log gist: https://gist.github.com/Sudiukil/f6ac48877bdaebb09dcde3a1a89ced78
- Additional info: Gitea is behind a Nginx reverse proxy

## Description

I just updated my Gitea instance from 1.2.3 to 1.4.1. I created a new repository and after pushing some content on the master branch (following the same procedure as always), the web interface keeps showing the repository as empty (see attached screenshot). I tried cloning back the repository, all the files are here, as it should be.

## Screenshots

![2018-06-05-140159_1165x653_scrot](https://user-images.githubusercontent.com/5354318/40974888-5584510e-68c9-11e8-9f3e-4bfb474a73fa.png)

**Comment by daviian** [comment]
@Sudiukil Please update to the newest release 1.4.2, as it is fixed there with https://github.com/go-gitea/gitea/pull/4075

To fix the existing repo follow https://github.com/go-gitea/gitea/issues/3458#issuecomment-381531981

**Comment by Sudiukil** [comment]
@daviian Awesome work, it's fixed, thanks !

**Comment by ghost** [comment]
After updating and restarting it should magically work? I'm still having the issue after upgrading from 1.4.1 to 1.4.2. 

[Edit] Er, I guess I need to follow that fix. I'll see if my future moved over repos have the problem.

**Comment by cani1see** [comment]
I have a repo "HEAD refers to nonexistent ref", after migrate that repo , it shows empty, also every new repo shows empty , and new commit to exist repo don't get update.
