### ISSUE TITLE
Allow Picture in the WIKI

### ISSUE THREAD

**Issue by a7hybnj2** [go-gitea/gitea#4376]
I have tired several ways to make images show up in the wiki pages. Adding pictures to the markdown pages of the project.git is easy and I think the wiki should work the same way.

**Comment by jonasfranz** [comment]
You can add pictures and other files via git. Simply clone the wiki git repo, add your changes and push. You can reference those files by there relative path. For example `gitea.png` => `gitea.png`.

While testing this I discovered a bug which results in a wrong image link. I will send in a PR to fix this.

**Comment by lunny** [comment]
@JonasFranzDEV Is this fixed by #4377 ?

**Comment by jonasfranz** [comment]
The bug is fixed. But maybe @a7hybnj2 intended to have a easier way of uploading images to wiki. If this is true, @a7hybnj2 please create a new issue for that.

**Comment by a7hybnj2** [comment]
No I did not mean to make it easier. I did indeed upload pictures to the wiki via git and referenced those pictures with MD in the wiki files. This resulted in a logon popup to be displayed while accessing that page. When moving the same image and md file to my main project.git directory I was not prompted for a logon.

**Comment by SohnyBohny** [comment]
Images in wiki are still not working for me.
Using version 1.5.0-rc2 the URL includes 'raw' but I get http error 404 when accessing the image.

**Comment by bigassforce** [comment]
This works in Gitea version 1.10.2:

1. Save a new wiki page
2. Clone the wiki repository (http://localhost/org/repo.wiki.git)
3. Commit an image into the root directory and push to remote
4. Edit the wiki page and use the following markup: `![title](../raw/image.jpg)`

![gitea-wiki-page](https://user-images.githubusercontent.com/6777144/73649402-9dc1d580-4677-11ea-8e88-28268a8c8fe3.png)

![gitea-wiki-image](https://user-images.githubusercontent.com/6777144/73649425-aa462e00-4677-11ea-816f-17bf97d1022e.png)

**Comment by jhughes2112** [comment]
At least in my case, this works ONLY while in the Preview mode on the Wiki page editor.  As soon as you go to the actual wiki page, it is a 404.  Any idea how to get this link to work all the time?

**Comment by jhughes2112** [comment]
Reporting back... Solved my own problem.  At least in my config, the _preview_ shows up fine with one set of '../' but does not work when showing the page itself.  If I add '../../' the preview stops working but the page itself works fine.
