### ISSUE TITLE
API repos search should return private repos of that user

### ISSUE THREAD

**Issue by kasbah** [go-gitea/gitea#6183]
- Gitea version (or commit ref): 594f59169

## Description

Hello and thank you very much for your work on gitea!

I think that similarily to  #5310, `GET /repos/search` should return the private repos that the logged in user has access to. Currently only when you add `uid=$CURRENT_USER_ID` can you see the private repos (but then you don't see other people repos). 

Changing this would make it behave more like the current `/explore/repos` non-api endpoint.

**Comment by lunny** [comment]
Isn't that fixed by #5383 ?

**Comment by kasbah** [comment]
No, unless I am missing something. I am testing on latest master (v1.7.0-dev-241-g594f59169). I guess it only fixed it for `/orgs/:org/repos` not `/repos/search`.

**Comment by zeripath** [comment]
I can confirm that this is still an issue and affects the organisation view on the dashboard.

**Comment by kasbah** [comment]
@zeripath Could you clarify how it affects the organisation view on the dashboard? I had a look but couldn't find anything wrong there.

**Comment by zeripath** [comment]
OK, log in as arandomer2@mailinator.com with the same password on to http://try.gitea.io

arandomer2 has read access to TestOrgAnother, although TestOrgAnother/private-test-repository appears on arandomer2 dashboard take a look at:

https://try.gitea.io/org/TestOrgAnother/dashboard

**Comment by kasbah** [comment]
Ah I see. <del>Is that an experimental page or something? I am not even sure how to even get there through the UI. </del> Nevermind, figured out it's through the top left selection on the dashboard. Not sure what it's for though vs just the gitea.com/\<org-name\> page.

**Comment by zeripath** [comment]
It's supposed to give you the newsfeed for that organisation context. The + repository button would allow you to create a repository in that organisation by default if you're allowed to create repositories for that organisation.

**Comment by zeripath** [comment]
I don't think you're supposed to see the organisation repos in the right hand box unless you're in the organisation context either

**Comment by zeripath** [comment]
I think this is finally fixed by #6897 in 1.9
