### ISSUE TITLE
[Branch View] protected symbol shows up unintended when not logged in

### ISSUE THREAD

**Issue by 6543** [go-gitea/gitea#7576]
branches  shows  protected symbol if you arent signt in.

if you are loged in protected symbol is on corect places only  (doesnt mather if you only have read or wirte permissions)

**Comment by gary-kim** [comment]
There does seem to be a bug where the branches page will indicate that all branches are protected whether or not they are actually protected branches.

**Comment by 6543** [comment]
i think this is a bug in the go code (server side)

**Comment by 6543** [comment]
# Preview:
## with login
![login](https://ipfs.io/ipfs/QmawScNMXW1c7CPE39icXyeHDTKjrMBeMLvA8fvLHKGkmA)
## without login
![no login](https://ipfs.io/ipfs/QmXe6QLdGUxeW4fRRmYNXwugQkEJoEbZpdrdKsuLGP4poH)

**Comment by lunny** [comment]
This should be resolved by https://github.com/go-gitea/gitea/pull/7674

**Comment by 6543** [comment]
no it doesnt :( is it fixed at your test instance @lunny 
i tested master (d974c139b4a87a86254b3e4660b131152923f083)

**Comment by lunny** [comment]
@6543 right. The bug is still there when no login. @techknowlogick
